### ISSUE TITLE
Compiler bug when if(is...)/else if(is ...) is nested in while()

### ISSUE THREAD

**Issue by jpragey** [ceylon/ceylon-compiler#1918]
Compiling:
```ceylon
class Dummy() 
{
    value valList = LinkedList{1, 30.0, ""};
    while(exists current = valList.deleteFirst()) { // same with if or assert
        
        if(is Integer current) {
        }
        else if(is String current) { // can not find symbol 'current'
        }
    }
}
```
crashes the compiler:
```
source/org/app/run.ceylon:12: error: cannot find symbol
        else if(is String current) {
                          ^
  symbol:   variable current
  location: class Dummy
Note: Created module org.app/1.0.0
ceylon compile: Fatal error: The compiler exited abnormally (4) due to a bug in
the compiler.
Please report it:
 https://github.com/ceylon/ceylon-compiler/issues/new
Please include:

* the stacktrace printed below
* a description of what you were trying to compile.

Thank you!
com.redhat.ceylon.compiler.CompilerBugException: Bug
	at com.redhat.ceylon.compiler.CeylonCompileTool.handleExitCode(CeylonCompileTool.java:510)
	at com.redhat.ceylon.compiler.CeylonCompileTool.run(CeylonCompileTool.java:492)
	at com.redhat.ceylon.common.tools.CeylonTool.run(CeylonTool.java:367)
	at com.redhat.ceylon.common.tools.CeylonTool.execute(CeylonTool.java:304)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.redhat.ceylon.launcher.Launcher.runInJava7Checked(Launcher.java:107)
	at com.redhat.ceylon.launcher.Launcher.run(Launcher.java:37)
	at com.redhat.ceylon.launcher.Launcher.run(Launcher.java:30)
	at com.redhat.ceylon.launcher.Launcher.main(Launcher.java:23)
Caused by: java.lang.RuntimeException: Error generating bytecode for source/org/app/run.ceylon
	at com.redhat.ceylon.compiler.java.tools.LanguageCompiler.genCodeUnlessError(LanguageCompiler.java:784)
	at com.redhat.ceylon.compiler.java.tools.LanguageCompiler.genCode(LanguageCompiler.java:724)
	at com.sun.tools.javac.main.JavaCompiler.generate(JavaCompiler.java:1450)
	at com.redhat.ceylon.compiler.java.tools.LanguageCompiler.generate(LanguageCompiler.java:835)
	at com.sun.tools.javac.main.JavaCompiler.generate(JavaCompiler.java:1418)
	at com.sun.tools.javac.main.JavaCompiler.compile2(JavaCompiler.java:871)
	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:829)
	at com.redhat.ceylon.compiler.java.tools.LanguageCompiler.compile(LanguageCompiler.java:229)
	at com.redhat.ceylon.compiler.java.launcher.Main.compile(Main.java:650)
	at com.redhat.ceylon.compiler.java.launcher.Main.compile(Main.java:566)
	at com.redhat.ceylon.compiler.java.launcher.Main.compile(Main.java:556)
	at com.redhat.ceylon.compiler.CeylonCompileTool.run(CeylonCompileTool.java:491)
	... 10 more
Caused by: java.lang.AssertionError
	at com.sun.tools.javac.code.Symbol.clone(Symbol.java:131)
	at com.sun.tools.javac.jvm.Gen.binaryQualifier(Gen.java:296)
	at com.sun.tools.javac.jvm.Gen.visitIdent(Gen.java:2113)
	at com.sun.tools.javac.tree.JCTree$JCIdent.accept(JCTree.java:1707)
	at com.sun.tools.javac.jvm.Gen.genExpr(Gen.java:837)
	at com.sun.tools.javac.jvm.Gen.visitAssign(Gen.java:1786)
	at com.sun.tools.javac.tree.JCTree$JCAssign.accept(JCTree.java:1468)
	at com.sun.tools.javac.jvm.Gen.genExpr(Gen.java:837)
	at com.sun.tools.javac.jvm.Gen.visitTypeTest(Gen.java:2083)
	at com.sun.tools.javac.tree.JCTree$JCInstanceOf.accept(JCTree.java:1622)
	at com.sun.tools.javac.jvm.Gen.genExpr(Gen.java:837)
	at com.sun.tools.javac.jvm.Gen.genCond(Gen.java:817)
	at com.sun.tools.javac.jvm.Gen.genCond(Gen.java:770)
	at com.sun.tools.javac.jvm.Gen.visitIf(Gen.java:1610)
	at com.sun.tools.javac.tree.JCTree$JCIf.accept(JCTree.java:1142)
	at com.sun.tools.javac.jvm.Gen.genDef(Gen.java:684)
	at com.sun.tools.javac.jvm.Gen.genStat(Gen.java:719)
	at com.sun.tools.javac.jvm.Gen.genStat(Gen.java:705)
	at com.sun.tools.javac.jvm.Gen.genStats(Gen.java:756)
	at com.sun.tools.javac.jvm.Gen.visitBlock(Gen.java:1031)
	at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:783)
	at com.sun.tools.javac.jvm.Gen.genDef(Gen.java:684)
	at com.sun.tools.javac.jvm.Gen.genStat(Gen.java:719)
	at com.sun.tools.javac.jvm.Gen.genStat(Gen.java:705)
	at com.sun.tools.javac.jvm.Gen.visitIf(Gen.java:1621)
	at com.sun.tools.javac.tree.JCTree$JCIf.accept(JCTree.java:1142)
	at com.sun.tools.javac.jvm.Gen.genDef(Gen.java:684)
	at com.sun.tools.javac.jvm.Gen.genStat(Gen.java:719)
	at com.sun.tools.javac.jvm.Gen.genStat(Gen.java:705)
	at com.sun.tools.javac.jvm.Gen.genStats(Gen.java:756)
	at com.sun.tools.javac.jvm.Gen.visitBlock(Gen.java:1031)
	at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:783)
	at com.sun.tools.javac.jvm.Gen.genDef(Gen.java:684)
	at com.sun.tools.javac.jvm.Gen.genStat(Gen.java:719)
	at com.sun.tools.javac.jvm.Gen.genStat(Gen.java:705)
	at com.sun.tools.javac.jvm.Gen.visitIf(Gen.java:1615)
	at com.sun.tools.javac.tree.JCTree$JCIf.accept(JCTree.java:1142)
	at com.sun.tools.javac.jvm.Gen.genDef(Gen.java:684)
	at com.sun.tools.javac.jvm.Gen.genStat(Gen.java:719)
	at com.sun.tools.javac.jvm.Gen.genStat(Gen.java:705)
	at com.sun.tools.javac.jvm.Gen.genStats(Gen.java:756)
	at com.sun.tools.javac.jvm.Gen.visitBlock(Gen.java:1031)
	at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:783)
	at com.sun.tools.javac.jvm.Gen.genDef(Gen.java:684)
	at com.sun.tools.javac.jvm.Gen.genStat(Gen.java:719)
	at com.sun.tools.javac.jvm.Gen.genStat(Gen.java:705)
	at com.sun.tools.javac.jvm.Gen.genLoop(Gen.java:1080)
	at com.sun.tools.javac.jvm.Gen.visitWhileLoop(Gen.java:1045)
	at com.sun.tools.javac.tree.JCTree$JCWhileLoop.accept(JCTree.java:839)
	at com.sun.tools.javac.jvm.Gen.genDef(Gen.java:684)
	at com.sun.tools.javac.jvm.Gen.genStat(Gen.java:719)
	at com.sun.tools.javac.jvm.Gen.genStat(Gen.java:705)
	at com.sun.tools.javac.jvm.Gen.visitLabelled(Gen.java:1108)
	at com.sun.tools.javac.tree.JCTree$JCLabeledStatement.accept(JCTree.java:936)
	at com.sun.tools.javac.jvm.Gen.genDef(Gen.java:684)
	at com.sun.tools.javac.jvm.Gen.genStat(Gen.java:719)
	at com.sun.tools.javac.jvm.Gen.genStat(Gen.java:705)
	at com.sun.tools.javac.jvm.Gen.genStats(Gen.java:756)
	at com.sun.tools.javac.jvm.Gen.visitBlock(Gen.java:1031)
	at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:783)
	at com.sun.tools.javac.jvm.Gen.genDef(Gen.java:684)
	at com.sun.tools.javac.jvm.Gen.genStat(Gen.java:719)
	at com.sun.tools.javac.jvm.Gen.genMethod(Gen.java:912)
	at com.sun.tools.javac.jvm.Gen.visitMethodDef(Gen.java:885)
	at com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:671)
	at com.sun.tools.javac.jvm.Gen.genDef(Gen.java:684)
	at com.sun.tools.javac.jvm.Gen.genClass(Gen.java:2246)
	at com.redhat.ceylon.compiler.java.tools.LanguageCompiler.genCodeUnlessError(LanguageCompiler.java:755)
	... 21 more
```
Same problem if `while()` is replaced by `if` or `assert`.

**Comment by FroMage** [comment]
This is actually another bug it seems, due to scopes and substitutions. Perhaps @tombentley can give me a hand? I'm a bit lost there.

**Comment by FroMage** [comment]
So what happens here is that we're not defining a new variable for the `is CAlias` test, and since we decompose the test in two `instanceof` the first one gets the right expression to test, but the second gets the name unsubstituted, due to a problem with scopes and substitution keys.

Hence the generated code looks like:

```java
    public Dummy2() {
        final .ceylon.language.List valList = (.ceylon.language.List).ceylon.language.nothing_.get_();
        loop_0: while (true) {
            .java.lang.Object current$0;
            if ((current$0 = valList.getFirst()) != null) {
                final .java.lang.Object current$1 = current$0;
                .java.lang.Object current$3;
                if ((current$3 = current$1) instanceof .com.redhat.ceylon.compiler.java.test.issues.bug19xx.B) {
                    final .com.redhat.ceylon.compiler.java.test.issues.bug19xx.B current$1$6 = (.com.redhat.ceylon.compiler.java.test.issues.bug19xx.B)current$3;
                } else {
                    if (current$1 instanceof .com.redhat.ceylon.compiler.java.test.issues.bug19xx.C || current instanceof .ceylon.language.Integer) {
                    }
                }
            } else {
                break loop_0;
            }
        }
    }
```

I don't quite get why the substitution key gets the wrong scope or how to fix it.

**Comment by FroMage** [comment]
OK, reassigning to @tombentley, perhaps he's luckier than I am :(

**Comment by FroMage** [comment]
Thanks @tombentley I would never have figured how to fix this!
