### ISSUE TITLE
Omitting class body causes null pointer exceptions

### ISSUE THREAD

**Issue by sadmac7000** [ceylon/ceylon-compiler#1997]
This (admittedly broken) code:
```ceylon
class Test(shared Integer a, shared Integer b, shared Integer c, shared Integer d);
```

Makes the compiler puke:
```
source/test/testme.ceylon:1: error: CompilerBoxingDeclarationVisitor caused an exception visiting ValueParameterDeclaration node: java.lang.NullPointerException at com.redhat.ceylon.compiler.java.codegen.CodegenUtil.getTopmostRefinedDeclaration(CodegenUtil.java:264)
class Test(shared Integer a, shared Integer b, shared Integer c, shared Integer
          ^
source/test/testme.ceylon:1: error: CompilerBoxingDeclarationVisitor caused an exception visiting AttributeDeclaration node: java.lang.NullPointerException at com.redhat.ceylon.compiler.java.codegen.CodegenUtil.getTopmostRefinedDeclaration(CodegenUtil.java:264)
class Test(shared Integer a, shared Integer b, shared Integer c, shared Integer
                         ^
source/test/testme.ceylon:1: error: CompilerBoxingDeclarationVisitor caused an exception visiting ValueParameterDeclaration node: java.lang.NullPointerException at com.redhat.ceylon.compiler.java.codegen.CodegenUtil.getTopmostRefinedDeclaration(CodegenUtil.java:264)
class Test(shared Integer a, shared Integer b, shared Integer c, shared Integer
                            ^
source/test/testme.ceylon:1: error: CompilerBoxingDeclarationVisitor caused an exception visiting AttributeDeclaration node: java.lang.NullPointerException at com.redhat.ceylon.compiler.java.codegen.CodegenUtil.getTopmostRefinedDeclaration(CodegenUtil.java:264)
class Test(shared Integer a, shared Integer b, shared Integer c, shared Integer
                                           ^
source/test/testme.ceylon:1: error: CompilerBoxingDeclarationVisitor caused an exception visiting ValueParameterDeclaration node: java.lang.NullPointerException at com.redhat.ceylon.compiler.java.codegen.CodegenUtil.getTopmostRefinedDeclaration(CodegenUtil.java:264)
class Test(shared Integer a, shared Integer b, shared Integer c, shared Integer
                                              ^
source/test/testme.ceylon:1: error: CompilerBoxingDeclarationVisitor caused an exception visiting AttributeDeclaration node: java.lang.NullPointerException at com.redhat.ceylon.compiler.java.codegen.CodegenUtil.getTopmostRefinedDeclaration(CodegenUtil.java:264)
class Test(shared Integer a, shared Integer b, shared Integer c, shared Integer
                                                             ^
source/test/testme.ceylon:1: error: CompilerBoxingDeclarationVisitor caused an exception visiting ValueParameterDeclaration node: java.lang.NullPointerException at com.redhat.ceylon.compiler.java.codegen.CodegenUtil.getTopmostRefinedDeclaration(CodegenUtil.java:264)
class Test(shared Integer a, shared Integer b, shared Integer c, shared Integer
                                                                ^
source/test/testme.ceylon:2: error: CompilerBoxingDeclarationVisitor caused an exception visiting AttributeDeclaration node: java.lang.NullPointerException at com.redhat.ceylon.compiler.java.codegen.CodegenUtil.getTopmostRefinedDeclaration(CodegenUtil.java:264)
        d);
       ^
source/test/testme.ceylon:1: error: missing class body or aliased class reference
class Test(shared Integer a, shared Integer b, shared Integer c, shared Integer
     ^
9 errors
Note: Created module test/0.0.1
ceylon compile: There were 9 errors
```

**Comment by FroMage** [comment]
Fixed!
