### ISSUE TITLE
Bug in the Java backend when splicing a tuple into superclass args

### ISSUE THREAD

**Issue by QrczakMK** [ceylon/ceylon-compiler#2007]
class Class1(Integer x) {}
class Class2() extends Class1(*[7]) {}

Result:

error: constructor Class1 in class Class1 cannot be applied to given types;
  required: long
  found: no arguments
  reason: actual and formal argument lists differ in length
source/play/Class2.ceylon:1: error: call to super must be first statement in constructor
class Class2() extends Class1(*[7]) {}
                                ^
Note: Created module play/1.0.0
ceylon compile: Fatal error: The compiler exited abnormally (4) due to a bug in
the compiler.
Please report it:
 https://github.com/ceylon/ceylon-compiler/issues/new
Please include:

* the stacktrace printed below
* a description of what you were trying to compile.

Thank you!
com.redhat.ceylon.compiler.CompilerBugException: Bug
	at com.redhat.ceylon.compiler.CeylonCompileTool.handleExitCode(CeylonCompileTool.java:472)
	at com.redhat.ceylon.compiler.CeylonCompileTool.run(CeylonCompileTool.java:454)
	at com.redhat.ceylon.common.tools.CeylonTool.run(CeylonTool.java:352)
	at com.redhat.ceylon.common.tools.CeylonTool.execute(CeylonTool.java:291)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.redhat.ceylon.launcher.Launcher.runInJava7Checked(Launcher.java:104)
	at com.redhat.ceylon.launcher.Launcher.run(Launcher.java:37)
	at com.redhat.ceylon.launcher.Launcher.run(Launcher.java:30)
	at com.redhat.ceylon.launcher.Launcher.main(Launcher.java:23)
Caused by: java.lang.NullPointerException
	at com.sun.tools.javac.comp.TransTypes.retype(TransTypes.java:160)
	at com.sun.tools.javac.comp.TransTypes.visitApply(TransTypes.java:605)
	at com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1323)
	at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
	at com.sun.tools.javac.comp.TransTypes.translate(TransTypes.java:429)
	at com.sun.tools.javac.comp.TransTypes.visitExec(TransTypes.java:568)
	at com.sun.tools.javac.tree.JCTree$JCExpressionStatement.accept(JCTree.java:1169)
	at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
	at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:70)
	at com.sun.tools.javac.tree.TreeTranslator.visitBlock(TreeTranslator.java:160)
	at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:783)
	at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
	at com.sun.tools.javac.comp.TransTypes.translate(TransTypes.java:429)
	at com.sun.tools.javac.comp.TransTypes.visitMethodDef(TransTypes.java:463)
	at com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:671)
	at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
	at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:70)
	at com.sun.tools.javac.tree.TreeTranslator.visitClassDef(TreeTranslator.java:134)
	at com.sun.tools.javac.comp.TransTypes.translateClass(TransTypes.java:882)
	at com.sun.tools.javac.comp.TransTypes.visitClassDef(TransTypes.java:450)
	at com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:593)
	at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
	at com.sun.tools.javac.comp.TransTypes.translate(TransTypes.java:429)
	at com.sun.tools.javac.comp.TransTypes.translateTopLevelClass(TransTypes.java:909)
	at com.sun.tools.javac.main.JavaCompiler.desugar(JavaCompiler.java:1376)
	at com.redhat.ceylon.compiler.java.tools.LanguageCompiler.desugar(LanguageCompiler.java:774)
	at com.sun.tools.javac.main.JavaCompiler.desugar(JavaCompiler.java:1272)
	at com.sun.tools.javac.main.JavaCompiler.compile2(JavaCompiler.java:871)
	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:829)
	at com.redhat.ceylon.compiler.java.tools.LanguageCompiler.compile(LanguageCompiler.java:227)
	at com.redhat.ceylon.compiler.java.launcher.Main.compile(Main.java:650)
	at com.redhat.ceylon.compiler.java.launcher.Main.compile(Main.java:566)
	at com.redhat.ceylon.compiler.java.launcher.Main.compile(Main.java:556)
	at com.redhat.ceylon.compiler.CeylonCompileTool.run(CeylonCompileTool.java:453)
	... 10 more

**Comment by tombentley** [comment]
Thanks for reporting.
