### ISSUE TITLE
Backend error for `let` that precedes a called void function

### ISSUE THREAD

**Issue by sgalles** [ceylon/ceylon-compiler#2014]
This code
```ceylon
shared void run(){
   void foo(){}
   value bar = let(a = 42) foo();
} 
```
compiled :
```
java.lang.RuntimeException: Error generating bytecode for source\bar\run.ceylon
        at com.redhat.ceylon.compiler.java.tools.LanguageCompiler.genCodeUnlessError(LanguageCompiler.java:784)
        at com.redhat.ceylon.compiler.java.tools.LanguageCompiler.genCode(LanguageCompiler.java:724)
        ...
Caused by: java.lang.AssertionError
        at com.sun.tools.javac.jvm.Items$Item.load(Items.java:207)
        at com.sun.tools.javac.jvm.Gen.visitLetExpr(Gen.java:2210)
        ...
```

**Comment by tombentley** [comment]
Should work now. Thanks @sgalles
