### ISSUE TITLE
method annotations in class annotations_ cannot be applied to given types

### ISSUE THREAD

**Issue by bjansen** [ceylon/ceylon-compiler#2029]
The following minimal sample does not compile:

```ceylon
import ceylon.language.meta {
    annotations
}
import ceylon.language.meta.declaration {
    ClassDeclaration,
    FunctionDeclaration
}
 
shared final annotation class A()
        satisfies OptionalAnnotation<A,FunctionDeclaration|ClassDeclaration> {
}
 
A? annos = annotations(`A`, nothing);
```
Compiler output:
```
bug.ceylon:13: warning: expression has type 'Nothing'
A? annos = annotations(`A`, nothing);
                           ^
bug.ceylon:13: error: method annotations in class annotations_ cannot be applied to given types;
A? annos = annotations(`A`, nothing);
           ^
  required: TypeDescriptor,TypeDescriptor,TypeDescriptor,Class<? extends ConstrainedAnnotation<? extends Value,? extends Values,? super ProgramElement>,?>,ProgramElement
  found: TypeDescriptor,TypeDescriptor,TypeDescriptor,Class<CAP#1,CAP#2>,Annotated
  reason: actual argument Class<CAP#1,CAP#2> cannot be converted to Class<? extends ConstrainedAnnotation<? extends ConstrainedAnnotation,? extends A,? super Annotated>,?> by method invocation conversion
  where Value,Values,ProgramElement are type-variables:
    Value extends ConstrainedAnnotation<? extends Value,? extends Values,? super ProgramElement> declared in method <Value,Values,ProgramElement>annotations(TypeDescriptor,TypeDescriptor,TypeDescriptor,Class<? extends ConstrainedAnnotation<? extends Value,? extends Values,? super ProgramElement>,?>,ProgramElement)
    Values extends Object declared in method <Value,Values,ProgramElement>annotations(TypeDescriptor,TypeDescriptor,TypeDescriptor,Class<? extends ConstrainedAnnotation<? extends Value,? extends Values,? super ProgramElement>,?>,ProgramElement)
    ProgramElement extends Annotated declared in method <Value,Values,ProgramElement>annotations(TypeDescriptor,TypeDescriptor,TypeDescriptor,Class<? extends ConstrainedAnnotation<? extends Value,? extends Values,? super ProgramElement>,?>,ProgramElement)
  where CAP#1,CAP#2 are fresh type-variables:
    CAP#1 extends A from capture of ? extends A
    CAP#2 extends Sequential<? extends Object> super: Empty from capture of ? super Empty
Note: Created module default
ceylon compile: There was 1 error
```

On a more complex code, when trying to compile https://github.com/bjansen/gyokuro I also get a fatal error:

```
ceylon compile: Fatal error: The compiler exited abnormally (4) due to a bug in
the compiler.
Please report it:
 https://github.com/ceylon/ceylon-compiler/issues/new
Please include:
 
* the stacktrace printed below
* a description of what you were trying to compile.
 
Thank you!
com.redhat.ceylon.compiler.CompilerBugException: Bug
	at com.redhat.ceylon.compiler.CeylonCompileTool.handleExitCode(CeylonCompileTool.java:495)
	at com.redhat.ceylon.compiler.CeylonCompileTool.run(CeylonCompileTool.java:477)
	at com.redhat.ceylon.common.tools.CeylonTool.run(CeylonTool.java:409)
	at com.redhat.ceylon.common.tools.CeylonTool.execute(CeylonTool.java:346)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.redhat.ceylon.launcher.Launcher.runInJava7Checked(Launcher.java:113)
	at com.redhat.ceylon.launcher.Launcher.run(Launcher.java:40)
	at com.redhat.ceylon.launcher.Launcher.run(Launcher.java:33)
	at com.redhat.ceylon.launcher.Launcher.main(Launcher.java:26)
Caused by: java.lang.AssertionError
	at com.sun.tools.javac.util.Assert.error(Assert.java:126)
	at com.sun.tools.javac.util.Assert.check(Assert.java:45)
	at com.sun.tools.javac.comp.TransTypes.visitApply(TransTypes.java:601)
	at com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1323)
	at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
	at com.sun.tools.javac.comp.TransTypes.translate(TransTypes.java:429)
	at com.sun.tools.javac.comp.TransTypes.visitTypeCast(TransTypes.java:668)
	at com.sun.tools.javac.tree.JCTree$JCTypeCast.accept(JCTree.java:1596)
	at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
	at com.sun.tools.javac.comp.TransTypes.translate(TransTypes.java:429)
	at com.sun.tools.javac.comp.TransTypes.visitTypeCast(TransTypes.java:668)
	at com.sun.tools.javac.tree.JCTree$JCTypeCast.accept(JCTree.java:1596)
	at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
	at com.sun.tools.javac.comp.TransTypes.translate(TransTypes.java:429)
	at com.sun.tools.javac.comp.TransTypes.visitAssign(TransTypes.java:642)
	at com.sun.tools.javac.tree.JCTree$JCAssign.accept(JCTree.java:1468)
	at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
	at com.sun.tools.javac.comp.TransTypes.translate(TransTypes.java:429)
	at com.sun.tools.javac.comp.TransTypes.visitBinary(TransTypes.java:660)
	at com.sun.tools.javac.tree.JCTree$JCBinary.accept(JCTree.java:1567)
	at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
	at com.sun.tools.javac.comp.TransTypes.translate(TransTypes.java:429)
	at com.sun.tools.javac.comp.TransTypes.visitIf(TransTypes.java:561)
	at com.sun.tools.javac.tree.JCTree$JCIf.accept(JCTree.java:1142)
	at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
	at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:70)
	at com.sun.tools.javac.tree.TreeTranslator.visitBlock(TreeTranslator.java:160)
	at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:783)
	at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
	at com.sun.tools.javac.comp.TransTypes.visitIf(TransTypes.java:562)
	at com.sun.tools.javac.tree.JCTree$JCIf.accept(JCTree.java:1142)
	at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
	at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:70)
	at com.sun.tools.javac.tree.TreeTranslator.visitBlock(TreeTranslator.java:160)
	at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:783)
	at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
	at com.sun.tools.javac.comp.TransTypes.visitIf(TransTypes.java:562)
	at com.sun.tools.javac.tree.JCTree$JCIf.accept(JCTree.java:1142)
	at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
	at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:70)
	at com.sun.tools.javac.tree.TreeTranslator.visitBlock(TreeTranslator.java:160)
	at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:783)
	at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
	at com.sun.tools.javac.comp.TransTypes.visitWhileLoop(TransTypes.java:499)
	at com.sun.tools.javac.tree.JCTree$JCWhileLoop.accept(JCTree.java:839)
	at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
	at com.sun.tools.javac.tree.TreeTranslator.visitLabelled(TreeTranslator.java:192)
	at com.sun.tools.javac.tree.JCTree$JCLabeledStatement.accept(JCTree.java:936)
	at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
	at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:70)
	at com.sun.tools.javac.tree.TreeTranslator.visitBlock(TreeTranslator.java:160)
	at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:783)
	at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
	at com.sun.tools.javac.comp.TransTypes.translate(TransTypes.java:429)
	at com.sun.tools.javac.comp.TransTypes.visitMethodDef(TransTypes.java:463)
	at com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:671)
	at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
	at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:70)
	at com.sun.tools.javac.tree.TreeTranslator.visitClassDef(TreeTranslator.java:134)
	at com.sun.tools.javac.comp.TransTypes.translateClass(TransTypes.java:890)
	at com.sun.tools.javac.comp.TransTypes.visitClassDef(TransTypes.java:450)
	at com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:593)
	at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
	at com.sun.tools.javac.comp.TransTypes.translate(TransTypes.java:429)
	at com.sun.tools.javac.comp.TransTypes.translateTopLevelClass(TransTypes.java:917)
	at com.sun.tools.javac.main.JavaCompiler.desugar(JavaCompiler.java:1376)
	at com.redhat.ceylon.compiler.java.tools.LanguageCompiler.desugar(LanguageCompiler.java:793)
	at com.sun.tools.javac.main.JavaCompiler.desugar(JavaCompiler.java:1272)
	at com.sun.tools.javac.main.JavaCompiler.compile2(JavaCompiler.java:871)
	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:829)
	at com.redhat.ceylon.compiler.java.tools.LanguageCompiler.compile(LanguageCompiler.java:229)
	at com.redhat.ceylon.compiler.java.launcher.Main.compile(Main.java:650)
	at com.redhat.ceylon.compiler.java.launcher.Main.compile(Main.java:566)
	at com.redhat.ceylon.compiler.java.launcher.Main.compile(Main.java:556)
	at com.redhat.ceylon.compiler.CeylonCompileTool.run(CeylonCompileTool.java:476)
	... 10 more
```

**Comment by lucaswerkmeister** [comment]
It compiles if you change the second type argument for `OptionalAnnotation` to either `ClassDeclaration` or `FunctionDeclaration`, so it looks like the union type is causing the problem.

**Comment by lucaswerkmeister** [comment]
You also get an error with an intersection type argument, e. g. `FunctionalDeclaration&Annotated`.

**Comment by tombentley** [comment]
@bjansen thanks for reporting. The original problem should be fixed now. If your more complex example still produces problems please open a separate issue.

**Comment by lucaswerkmeister** [comment]
I just updated and now https://github.com/bjansen/gyokuro builds without errors for me.

**Comment by bjansen** [comment]
I confirms this works as expected. Thanks for the quick fix!
