### ISSUE TITLE
Compiler bug when using advanced constructors and initializing shared class function member to local function.

### ISSUE THREAD

**Issue by sadmac7000** [ceylon/ceylon-compiler#2039]
Compiling this:
```ceylon
class TestClass {
    shared Object(Object?*) somefunc;
    shared new TestClass(Object(Object?*) somefunc) {
        this.somefunc = somefunc;
    }
    shared new Test2(Object ret) {
        Object somef(Object?* b) => ret;
        this.somefunc = somef;
    }
}
```

Gives this:
```
error: compiler bug: null at com.redhat.ceylon.compiler.java.codegen.Invocation.getParameterTypeForValueType(Invocation.java:167)
error: compiler bug: visitor didn't yield any result at com.redhat.ceylon.compiler.java.codegen.ExpressionTransformer.transformExpression(ExpressionTransformer.java:320)
error: compiler bug: visitor didn't yield any result at unknown
```

**Comment by tombentley** [comment]
Thanks for reporting @sadmac7000
