### ISSUE TITLE
war tool doesn't support maven imports

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-compiler#2059]
For example, if you have:

```ceylon
import "commons-codec:commons-codec" "1.9";
```

you get:

```
   [tomcat] Caused by: java.lang.RuntimeException: Missing module: commons-codec:commons-codec/1.9
   [tomcat] 	at com.redhat.ceylon.compiler.java.runtime.tools.impl.JavaRunnerImpl.loadModule(JavaRunnerImpl.java:212)
   [tomcat] 	at com.redhat.ceylon.compiler.java.runtime.tools.impl.JavaRunnerImpl.loadModule(JavaRunnerImpl.java:224)
   [tomcat] 	at com.redhat.ceylon.compiler.java.runtime.tools.impl.JavaRunnerImpl.<init>(JavaRunnerImpl.java:65)
   [tomcat] 	at com.redhat.ceylon.compiler.java.runtime.tools.CeylonToolProvider.getRunner(CeylonToolProvider.java:27)
   [tomcat] 	at com.redhat.ceylon.war.WarInitializer.initialize(WarInitializer.java:85)
```

The reason is for this is that, in the flat repository created by the war tool, maven modules are named using only the artifact name, such as `commons-codec.jar`, rather than `group:artifact`, like `commons-codec:commons-codec.jar`.

**Comment by jvasileff** [comment]
So the **idea** of a patch for this is below. I'm not submitting this as a pull request since the code below does not include  sanitizing of filenames.

```diff
diff --git a/src/com/redhat/ceylon/tools/war/CeylonWarTool.java b/src/com/redhat/ceylon/tools/war/CeylonWarTool.java
index 8303fbb..1a84c82 100644
--- a/src/com/redhat/ceylon/tools/war/CeylonWarTool.java
+++ b/src/com/redhat/ceylon/tools/war/CeylonWarTool.java
@@ -12,6 +12,7 @@ import java.net.MalformedURLException;
 import java.net.URL;
 import java.util.ArrayList;
 import java.util.List;
+import java.util.Map;
 import java.util.Properties;
 import java.util.jar.JarOutputStream;
 import java.util.zip.ZipEntry;
@@ -195,21 +196,21 @@ public class CeylonWarTool extends ModuleLoadingTool {

        protected void addLibEntries() throws MalformedURLException {
                final List<String> libs = new ArrayList<>();
-               
-               for (ArtifactResult module : this.loadedModules.values()) {
+
+               for (Map.Entry<String, ArtifactResult> entry : this.loadedModules.entrySet()) {
+                       ArtifactResult module = entry.getValue();
                        if (module == null) {
                                // it's an optional, missing module (likely java.*)
                                continue;
                        }

                        final File artifact = module.artifact();
-                       String name = artifact.getName();
+                       final String moduleName = entry.getKey();
+
+                       // use "-" for the version separator
+                       // use ".jar" so they'll get loaded by the container classloader
+                       final String name = moduleName.replace('/', '-') + ".jar";

-                       if (name.endsWith(".car")) {
-                               // turn cars into jars so they'll get loaded by the container classloader
-                               name = name.substring(0, name.length() - 4) + ".jar";
-                       }
-                       
                        addSpec(new URLEntrySpec(artifact.toURI().toURL(),
                                                        "WEB-INF/lib/" + name));
                        libs.add(name);
-- 
2.2.1
```

**Comment by jvasileff** [comment]
Closing since the PR was merged. Thanks!
