### ISSUE TITLE
`ceylon compile default` gives exception if no code is found

### ISSUE THREAD

**Issue by quintesse** [ceylon/ceylon-compiler#2071]
```
$ ceylon compile default
ceylon compile: no source files or modules
Usage: ceylon compile <options> <source files> <module names>
use --help for a list of possible options
ceylon compile: Fatal error: The compiler exited abnormally (2) due to a bug in
the compiler.
Please report it:
 https://github.com/ceylon/ceylon-compiler/issues/new
Please include:

* a description of what you were trying to compile.

Thank you!
com.redhat.ceylon.compiler.CompilerBugException: Bug
	at com.redhat.ceylon.compiler.CeylonCompileTool.handleExitCode(CeylonCompileTool.java:496)
	at com.redhat.ceylon.compiler.CeylonCompileTool.run(CeylonCompileTool.java:478)
	at com.redhat.ceylon.common.tools.CeylonTool.run(CeylonTool.java:409)
	at com.redhat.ceylon.common.tools.CeylonTool.execute(CeylonTool.java:346)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.redhat.ceylon.launcher.Launcher.runInJava7Checked(Launcher.java:113)
	at com.redhat.ceylon.launcher.Launcher.run(Launcher.java:40)
	at com.redhat.ceylon.launcher.Launcher.run(Launcher.java:33)
	at com.redhat.ceylon.launcher.Launcher.main(Launcher.java:26)
```

**Comment by quintesse** [comment]
Opened here by accident. Closing. See ceylon/ceylon-common#51
