### ISSUE TITLE
ModelError: Expected type or function or value

### ISSUE THREAD

**Issue by marvelous** [ceylon/ceylon-compiler#2075]
I have the following snipplet that compiles fine but throws when run.

import ceylon.language.meta.declaration {
	FunctionDeclaration,
	ValueDeclaration
}
shared final annotation class MyAnnotation(shared FunctionDeclaration fun)
		satisfies OptionalAnnotation&lt;MyAnnotation,ValueDeclaration> {}
shared annotation MyAnnotation myAnnotation(FunctionDeclaration fun) => MyAnnotation(fun);

myAnnotation (\`function run`)
shared Anything x = 0;

shared void run() {
	print(\`x`.declaration.annotations&lt;MyAnnotation>());
}

Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.redhat.ceylon.launcher.Launcher.runInJava7Checked(Launcher.java:104)
	at com.redhat.ceylon.launcher.Launcher.run(Launcher.java:37)
	at com.redhat.ceylon.launcher.Launcher.run(Launcher.java:30)
	at com.redhat.ceylon.launcher.Launcher.main(Launcher.java:23)
Caused by: com.redhat.ceylon.compiler.java.runtime.metamodel.ModelError: While reflectively instantiating class MyAnnotation on element value x
	at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.newModelError(Metamodel.java:1448)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.addAnnotation(Metamodel.java:796)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.annotations(Metamodel.java:850)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.annotations(Metamodel.java:836)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.FreeNestableDeclaration.annotations(FreeNestableDeclaration.java:92)
	at run_.run(test.ceylon:13)
	at run_.main(test.ceylon)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at ceylon.modules.api.runtime.SecurityActions.invokeRunInternal(SecurityActions.java:58)
	at ceylon.modules.api.runtime.SecurityActions.invokeRun(SecurityActions.java:48)
	at ceylon.modules.api.runtime.AbstractRuntime.invokeRun(AbstractRuntime.java:101)
	at ceylon.modules.api.runtime.AbstractRuntime.execute(AbstractRuntime.java:167)
	at ceylon.modules.api.runtime.AbstractRuntime.execute(AbstractRuntime.java:151)
	at ceylon.modules.Main.execute(Main.java:69)
	at ceylon.modules.Main.main(Main.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.jboss.modules.Module.run(Module.java:312)
	at org.jboss.modules.Main.main(Main.java:460)
	at ceylon.modules.bootstrap.CeylonRunTool.run(CeylonRunTool.java:208)
	at com.redhat.ceylon.common.tools.CeylonTool.run(CeylonTool.java:352)
	at com.redhat.ceylon.common.tools.CeylonTool.execute(CeylonTool.java:291)
	... 8 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.addAnnotation(Metamodel.java:789)
	... 33 more
Caused by: com.redhat.ceylon.compiler.java.runtime.metamodel.ModelError: Expected type or function or value at index 23: ::unversioned:default:.:Frun
	at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.newModelError(Metamodel.java:1448)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.newModelError(Metamodel.java:1443)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.DeclarationParser.parseError(DeclarationParser.java:52)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.DeclarationParser.declaration(DeclarationParser.java:181)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.DeclarationParser.package_(DeclarationParser.java:165)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.DeclarationParser.module(DeclarationParser.java:109)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.DeclarationParser.ref(DeclarationParser.java:75)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.parseMetamodelReference(Metamodel.java:1005)
	at MyAnnotation.&lt;init>(test.ceylon:5)
	... 38 more
ABRT problem creation: 'success'

**Comment by tombentley** [comment]
@marvelous it looks like this bug only affects the default module, so if you move your code to a "proper" module it should work.

**Comment by tombentley** [comment]
Thanks for reporting.

**Comment by marvelous** [comment]
Thanks for fixing so quickly. You are right that this code works in a proper module, but it was a reduced case of a much more complex program that is failing with the same stacktrace although it is in a proper module. Is there a nightly build to test if the commit fixes also my more complex program?

**Comment by quintesse** [comment]
@marvelous There are no nightly builds right now, hopefully that will change once we release 1.2 (Real Soon Now). Right now the only way is to follow the steps described here: http://www.ceylon-lang.org/code/contribute/
HTH
