### ISSUE TITLE
An exception has occurred in the compiler (ceylonc 1.1.0 (Ultimate Ship The Second)).

### ISSUE THREAD

**Issue by marvelous** [ceylon/ceylon-compiler#2085]
Compiling the following program:
```
interface Interface {
	shared class SharedGeneric<TypeArgument>() {}
}

class Class() satisfies Interface {
}
```
gives me the following output:
```
An exception has occurred in the compiler (ceylonc 1.1.0 (Ultimate Ship The Second)).
java.lang.RuntimeException: Error generating bytecode for source/test/impl.ceylon
	at com.redhat.ceylon.compiler.java.tools.LanguageCompiler.genCodeUnlessError(LanguageCompiler.java:765)
	at com.redhat.ceylon.compiler.java.tools.LanguageCompiler.genCode(LanguageCompiler.java:705)
	at com.sun.tools.javac.main.JavaCompiler.generate(JavaCompiler.java:1450)
	at com.redhat.ceylon.compiler.java.tools.LanguageCompiler.generate(LanguageCompiler.java:816)
	at com.sun.tools.javac.main.JavaCompiler.generate(JavaCompiler.java:1418)
	at com.sun.tools.javac.main.JavaCompiler.compile2(JavaCompiler.java:871)
	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:829)
	at com.redhat.ceylon.compiler.java.tools.LanguageCompiler.compile(LanguageCompiler.java:227)
	at com.redhat.ceylon.compiler.java.launcher.Main.compile(Main.java:650)
	at com.redhat.ceylon.compiler.java.launcher.Main.compile(Main.java:566)
	at com.redhat.ceylon.compiler.java.launcher.Main.compile(Main.java:556)
	at com.redhat.ceylon.compiler.CeylonCompileTool.run(CeylonCompileTool.java:453)
	at com.redhat.ceylon.common.tools.CeylonTool.run(CeylonTool.java:352)
	at com.redhat.ceylon.common.tools.CeylonTool.execute(CeylonTool.java:291)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.redhat.ceylon.launcher.Launcher.runInJava7Checked(Launcher.java:104)
	at com.redhat.ceylon.launcher.Launcher.run(Launcher.java:37)
	at com.redhat.ceylon.launcher.Launcher.run(Launcher.java:30)
	at com.redhat.ceylon.launcher.Launcher.main(Launcher.java:23)
Caused by: java.lang.AssertionError: typeSig 19
	at com.sun.tools.javac.jvm.ClassWriter.assembleSig(ClassWriter.java:367)
	at com.sun.tools.javac.jvm.ClassWriter.assembleSig(ClassWriter.java:413)
	at com.sun.tools.javac.jvm.ClassWriter.assembleClassSig(ClassWriter.java:405)
	at com.sun.tools.javac.jvm.ClassWriter.assembleSig(ClassWriter.java:310)
	at com.sun.tools.javac.jvm.ClassWriter.assembleSig(ClassWriter.java:323)
	at com.sun.tools.javac.jvm.ClassWriter.assembleSig(ClassWriter.java:358)
	at com.sun.tools.javac.jvm.ClassWriter.typeSig(ClassWriter.java:438)
	at com.sun.tools.javac.jvm.ClassWriter.writeMemberAttrs(ClassWriter.java:717)
	at com.sun.tools.javac.jvm.ClassWriter.writeMethod(ClassWriter.java:1032)
	at com.sun.tools.javac.jvm.ClassWriter.writeMethods(ClassWriter.java:1496)
	at com.sun.tools.javac.jvm.ClassWriter.writeClassFile(ClassWriter.java:1579)
	at com.sun.tools.javac.jvm.ClassWriter.writeClass(ClassWriter.java:1514)
	at com.redhat.ceylon.compiler.java.codegen.CeylonClassWriter.writeClass(CeylonClassWriter.java:63)
	at com.redhat.ceylon.compiler.java.tools.LanguageCompiler.genCodeUnlessError(LanguageCompiler.java:755)
	... 21 more
Note: Created module test/1.0.0
ceylon compile: Fatal error: The compiler exited abnormally (4) due to a bug in
the compiler.
Please report it:
 https://github.com/ceylon/ceylon-compiler/issues/new
Please include:

* the stacktrace printed below
* a description of what you were trying to compile.

Thank you!
com.redhat.ceylon.compiler.CompilerBugException: Bug
	at com.redhat.ceylon.compiler.CeylonCompileTool.handleExitCode(CeylonCompileTool.java:472)
	at com.redhat.ceylon.compiler.CeylonCompileTool.run(CeylonCompileTool.java:454)
	at com.redhat.ceylon.common.tools.CeylonTool.run(CeylonTool.java:352)
	at com.redhat.ceylon.common.tools.CeylonTool.execute(CeylonTool.java:291)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.redhat.ceylon.launcher.Launcher.runInJava7Checked(Launcher.java:104)
	at com.redhat.ceylon.launcher.Launcher.run(Launcher.java:37)
	at com.redhat.ceylon.launcher.Launcher.run(Launcher.java:30)
	at com.redhat.ceylon.launcher.Launcher.main(Launcher.java:23)
Caused by: java.lang.RuntimeException: Error generating bytecode for source/test/impl.ceylon
	at com.redhat.ceylon.compiler.java.tools.LanguageCompiler.genCodeUnlessError(LanguageCompiler.java:765)
	at com.redhat.ceylon.compiler.java.tools.LanguageCompiler.genCode(LanguageCompiler.java:705)
	at com.sun.tools.javac.main.JavaCompiler.generate(JavaCompiler.java:1450)
	at com.redhat.ceylon.compiler.java.tools.LanguageCompiler.generate(LanguageCompiler.java:816)
	at com.sun.tools.javac.main.JavaCompiler.generate(JavaCompiler.java:1418)
	at com.sun.tools.javac.main.JavaCompiler.compile2(JavaCompiler.java:871)
	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:829)
	at com.redhat.ceylon.compiler.java.tools.LanguageCompiler.compile(LanguageCompiler.java:227)
	at com.redhat.ceylon.compiler.java.launcher.Main.compile(Main.java:650)
	at com.redhat.ceylon.compiler.java.launcher.Main.compile(Main.java:566)
	at com.redhat.ceylon.compiler.java.launcher.Main.compile(Main.java:556)
	at com.redhat.ceylon.compiler.CeylonCompileTool.run(CeylonCompileTool.java:453)
	... 10 more
Caused by: java.lang.AssertionError: typeSig 19
	at com.sun.tools.javac.jvm.ClassWriter.assembleSig(ClassWriter.java:367)
	at com.sun.tools.javac.jvm.ClassWriter.assembleSig(ClassWriter.java:413)
	at com.sun.tools.javac.jvm.ClassWriter.assembleClassSig(ClassWriter.java:405)
	at com.sun.tools.javac.jvm.ClassWriter.assembleSig(ClassWriter.java:310)
	at com.sun.tools.javac.jvm.ClassWriter.assembleSig(ClassWriter.java:323)
	at com.sun.tools.javac.jvm.ClassWriter.assembleSig(ClassWriter.java:358)
	at com.sun.tools.javac.jvm.ClassWriter.typeSig(ClassWriter.java:438)
	at com.sun.tools.javac.jvm.ClassWriter.writeMemberAttrs(ClassWriter.java:717)
	at com.sun.tools.javac.jvm.ClassWriter.writeMethod(ClassWriter.java:1032)
	at com.sun.tools.javac.jvm.ClassWriter.writeMethods(ClassWriter.java:1496)
	at com.sun.tools.javac.jvm.ClassWriter.writeClassFile(ClassWriter.java:1579)
	at com.sun.tools.javac.jvm.ClassWriter.writeClass(ClassWriter.java:1514)
	at com.redhat.ceylon.compiler.java.codegen.CeylonClassWriter.writeClass(CeylonClassWriter.java:63)
	at com.redhat.ceylon.compiler.java.tools.LanguageCompiler.genCodeUnlessError(LanguageCompiler.java:755)
	... 21 more
```

**Comment by quintesse** [comment]
This is already fixed in the current version in `master`. Closing.
