### ISSUE TITLE
Build of ceylon/ceylon-ide-common fails with "compiler bug" errors

### ISSUE THREAD

**Issue by davidfestal** [ceylon/ceylon-compiler#2088]
The https://github.com/ceylon/ceylon-ide-common project, which was building correctly some days ago, now produces those errors during Ceylon build, either from the CLI or from the IDE :
```
source/com/redhat/ceylon/ide/common/phasedUnits.ceylon:119: warning: expression has type 'Nothing'
    shared actual Unit newUnit() => nothing;
                                   ^
source/com/redhat/ceylon/ide/common/ModulesScanner.ceylon:46: warning: expression has type 'Nothing'
shared abstract class IdeModuleManager() extends LazyModuleManager(nothing) {
                                                                  ^
source/com/redhat/ceylon/ide/common/ModulesScanner.ceylon:53: warning: expression has type 'Nothing'
    shared variable Boolean projectModule = nothing;
                                           ^
source/com/redhat/ceylon/ide/common/ModulesScanner.ceylon:54: warning: expression has type 'Nothing'
    shared {IdeModule*} moduleInReferencingProjects => nothing;
                                                      ^
test-source/test/com/redhat/ceylon/ide/common/vfs/zip.ceylon:24: warning: expression has type 'Nothing'
                                else nothing;
                                    ^
test-source/test/com/redhat/ceylon/ide/common/vfs/zip.ceylon:26: warning: expression has type 'Nothing'
    shared actual Path rootCeylonPath = createZipFileSystem(sourceZip).rootPaths.first else nothing;
                                                                                           ^
test-source/test/com/redhat/ceylon/ide/common/vfs/zip.ceylon:42: error: compiler bug: getSupertypes() not defined for union types or Nothing at com.redhat.ceylon.compiler.typechecker.model.ProducedType.getSupertypes(ProducedType.java:731)
}
^
test-source/test/com/redhat/ceylon/ide/common/vfs/zip.ceylon:42: error: compiler bug: visitor didn't yield any result at com.redhat.ceylon.compiler.java.codegen.ExpressionTransformer.transformExpression(ExpressionTransformer.java:324)
}
^
test-source/test/com/redhat/ceylon/ide/common/vfs/zip.ceylon:42: error: compiler bug: visitor didn't yield any result at unknown
}
^
``` 

Note that the `Nothing`-related warnings are expected, but that should not produce any back-end error afaik.

This seems quite critical IMO, since I don't see anything special in this code.

**Comment by tombentley** [comment]
When compiling from the CLI I got the same error location are you, but that appears to be bogus, because attaching a debugger it seems that exception is thrown when transforming the `Tree.Variable` in the `Tree.Let` on line 180 of `CeylonProjectConfig.ceylon`. 

The compiler is trying to determine whether it needs to apply variance casts. To do this asks the expression type `{String*}?` for its supertypes, and that is apparently a bit of a no-no.

**Comment by tombentley** [comment]
Should now be fixed
