### ISSUE TITLE
ceylon doc: NoSuchMethodException

### ISSUE THREAD

**Issue by jpragey** [ceylon/ceylon-compiler#2094]
Hi,
Running "ceylon doc" on 
``` ceylon
import ceylon.file {
	File,
	Path
}

shared class FileResourceLoader(
	Path path
) {
	String loadFile() {
		if(is File file= path.resource) {
			return "";
		} else {
			return "";
		}
	}
}
```
causes:
```
java.lang.NoSuchMethodException: com.sun.proxy.$Proxy41.reason()
	at java.lang.Class.getMethod(Class.java:1670)
	at com.redhat.ceylon.compiler.loader.impl.reflect.mirror.ReflectionAnnotation.getValue(ReflectionAnnotation.java:41)
	at com.redhat.ceylon.compiler.loader.LanguageAnnotation$6.makeFromCeylonAnnotation(LanguageAnnotation.java:86)
	at com.redhat.ceylon.compiler.loader.AbstractModelLoader.setAnnotations(AbstractModelLoader.java:2357)
	at com.redhat.ceylon.compiler.loader.AbstractModelLoader.addMethod(AbstractModelLoader.java:2525)
	at com.redhat.ceylon.compiler.loader.AbstractModelLoader.complete(AbstractModelLoader.java:2092)
	at com.redhat.ceylon.compiler.loader.AbstractModelLoader.complete(AbstractModelLoader.java:1901)
	at com.redhat.ceylon.compiler.loader.model.LazyInterface.load(LazyInterface.java:106)
	at com.redhat.ceylon.compiler.loader.model.LazyInterface.getExtendedTypeDeclaration(LazyInterface.java:177)
	at com.redhat.ceylon.compiler.typechecker.model.TypeDeclaration.getSupertypeDeclarations(TypeDeclaration.java:926)
	at com.redhat.ceylon.compiler.typechecker.model.Util.addToIntersection(Util.java:1019)
	at com.redhat.ceylon.compiler.typechecker.model.Util.addToIntersection(Util.java:984)
	at com.redhat.ceylon.compiler.typechecker.model.Util.intersectionType(Util.java:1434)
	at com.redhat.ceylon.compiler.typechecker.analyzer.ExpressionVisitor.narrow(ExpressionVisitor.java:727)
	at com.redhat.ceylon.compiler.typechecker.analyzer.ExpressionVisitor.visit(ExpressionVisitor.java:693)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$IsCondition.visit(Tree.java:4280)
	at com.redhat.ceylon.compiler.typechecker.tree.Walker.walkConditionList(Walker.java:985)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$ConditionList.visitChildren(Tree.java:4142)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visitAny(Visitor.java:10)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:158)
	at com.redhat.ceylon.compiler.typechecker.analyzer.ExpressionVisitor.visit(ExpressionVisitor.java:601)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$ConditionList.visit(Tree.java:4134)
	at com.redhat.ceylon.compiler.typechecker.tree.Walker.walkIfClause(Walker.java:798)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$IfClause.visitChildren(Tree.java:3441)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visitAny(Visitor.java:10)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:127)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:133)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$IfClause.visit(Tree.java:3433)
	at com.redhat.ceylon.compiler.typechecker.tree.Walker.walkIfStatement(Walker.java:790)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$IfStatement.visitChildren(Tree.java:3412)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visitAny(Visitor.java:10)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:114)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:115)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:117)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:126)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:132)
	at com.redhat.ceylon.compiler.typechecker.analyzer.ExpressionVisitor.visit(ExpressionVisitor.java:6731)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$IfStatement.visit(Tree.java:3404)
	at com.redhat.ceylon.compiler.typechecker.tree.Walker.walkBody(Walker.java:413)
	at com.redhat.ceylon.compiler.typechecker.tree.Walker.walkBlock(Walker.java:418)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$Block.visitChildren(Tree.java:1754)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visitAny(Visitor.java:10)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:67)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:68)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$Block.visit(Tree.java:1746)
	at com.redhat.ceylon.compiler.typechecker.tree.CustomTree$MethodDefinition.visitChildren(CustomTree.java:160)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visitAny(Visitor.java:10)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:114)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:115)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:26)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:48)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:53)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:54)
	at com.redhat.ceylon.compiler.typechecker.analyzer.ExpressionVisitor.visit(ExpressionVisitor.java:1699)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$MethodDefinition.visit(Tree.java:1341)
	at com.redhat.ceylon.compiler.typechecker.tree.Walker.walkBody(Walker.java:413)
	at com.redhat.ceylon.compiler.typechecker.tree.Walker.walkClassBody(Walker.java:422)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$ClassBody.visitChildren(Tree.java:1782)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visitAny(Visitor.java:10)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:67)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:69)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$ClassBody.visit(Tree.java:1774)
	at com.redhat.ceylon.compiler.typechecker.tree.CustomTree$ClassDefinition.visitChildren(CustomTree.java:207)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visitAny(Visitor.java:10)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:114)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:115)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:26)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:28)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:29)
	at com.redhat.ceylon.compiler.typechecker.analyzer.ExpressionVisitor.visit(ExpressionVisitor.java:1759)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:40)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:41)
	at com.redhat.ceylon.compiler.typechecker.analyzer.ExpressionVisitor.visit(ExpressionVisitor.java:1751)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$ClassDefinition.visit(Tree.java:937)
	at com.redhat.ceylon.compiler.typechecker.tree.Walker.walkCompilationUnit(Walker.java:30)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$CompilationUnit.visitChildren(Tree.java:30)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visitAny(Visitor.java:10)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:12)
	at com.redhat.ceylon.compiler.typechecker.analyzer.ExpressionVisitor.visit(ExpressionVisitor.java:150)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$CompilationUnit.visit(Tree.java:22)
	at com.redhat.ceylon.compiler.typechecker.context.PhasedUnit.analyseTypes(PhasedUnit.java:338)
	at com.redhat.ceylon.compiler.typechecker.TypeChecker.executePhases(TypeChecker.java:164)
	at com.redhat.ceylon.compiler.typechecker.TypeChecker.process(TypeChecker.java:127)
	at com.redhat.ceylon.compiler.typechecker.TypeChecker.process(TypeChecker.java:122)
	at com.redhat.ceylon.ceylondoc.CeylonDocTool.initialize(CeylonDocTool.java:412)
	at com.redhat.ceylon.common.tool.ToolFactory$ArgumentProcessor.invokeInitialize(ToolFactory.java:381)
	at com.redhat.ceylon.common.tool.ToolFactory$ArgumentProcessor.processArguments(ToolFactory.java:261)
	at com.redhat.ceylon.common.tool.ToolFactory.bindArguments(ToolFactory.java:432)
	at com.redhat.ceylon.common.tool.ToolFactory.bindArguments(ToolFactory.java:137)
	at com.redhat.ceylon.common.tools.CeylonTool.getTool(CeylonTool.java:501)
	at com.redhat.ceylon.common.tools.CeylonTool.getTools(CeylonTool.java:479)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.redhat.ceylon.launcher.Launcher.runInJava7Checked(Launcher.java:89)
	at com.redhat.ceylon.launcher.Launcher.run(Launcher.java:40)
	at com.redhat.ceylon.launcher.Launcher.run(Launcher.java:33)
	at com.redhat.ceylon.launcher.Launcher.main(Launcher.java:26)
java.lang.NoSuchMethodException: com.sun.proxy.$Proxy41.reason()
	at java.lang.Class.getMethod(Class.java:1670)
	at com.redhat.ceylon.compiler.loader.impl.reflect.mirror.ReflectionAnnotation.getValue(ReflectionAnnotation.java:41)
	at com.redhat.ceylon.compiler.loader.LanguageAnnotation$6.makeFromCeylonAnnotation(LanguageAnnotation.java:86)
	at com.redhat.ceylon.compiler.loader.AbstractModelLoader.setAnnotations(AbstractModelLoader.java:2357)
	at com.redhat.ceylon.compiler.loader.AbstractModelLoader.addMethod(AbstractModelLoader.java:2525)
	at com.redhat.ceylon.compiler.loader.AbstractModelLoader.complete(AbstractModelLoader.java:2092)
	at com.redhat.ceylon.compiler.loader.AbstractModelLoader.complete(AbstractModelLoader.java:1901)
	at com.redhat.ceylon.compiler.loader.model.LazyInterface.load(LazyInterface.java:106)
	at com.redhat.ceylon.compiler.loader.model.LazyInterface.getExtendedTypeDeclaration(LazyInterface.java:177)
	at com.redhat.ceylon.compiler.typechecker.model.TypeDeclaration.getSupertypeDeclarations(TypeDeclaration.java:926)
	at com.redhat.ceylon.compiler.typechecker.model.Util.addToIntersection(Util.java:1019)
	at com.redhat.ceylon.compiler.typechecker.model.Util.addToIntersection(Util.java:984)
	at com.redhat.ceylon.compiler.typechecker.model.Util.intersectionType(Util.java:1434)
	at com.redhat.ceylon.compiler.typechecker.analyzer.ExpressionVisitor.narrow(ExpressionVisitor.java:727)
	at com.redhat.ceylon.compiler.typechecker.analyzer.ExpressionVisitor.visit(ExpressionVisitor.java:693)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$IsCondition.visit(Tree.java:4280)
	at com.redhat.ceylon.compiler.typechecker.tree.Walker.walkConditionList(Walker.java:985)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$ConditionList.visitChildren(Tree.java:4142)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visitAny(Visitor.java:10)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:158)
	at com.redhat.ceylon.compiler.typechecker.analyzer.ExpressionVisitor.visit(ExpressionVisitor.java:601)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$ConditionList.visit(Tree.java:4134)
	at com.redhat.ceylon.compiler.typechecker.tree.Walker.walkIfClause(Walker.java:798)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$IfClause.visitChildren(Tree.java:3441)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visitAny(Visitor.java:10)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:127)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:133)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$IfClause.visit(Tree.java:3433)
	at com.redhat.ceylon.compiler.typechecker.tree.Walker.walkIfStatement(Walker.java:790)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$IfStatement.visitChildren(Tree.java:3412)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visitAny(Visitor.java:10)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:114)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:115)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:117)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:126)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:132)
	at com.redhat.ceylon.compiler.typechecker.analyzer.ExpressionVisitor.visit(ExpressionVisitor.java:6731)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$IfStatement.visit(Tree.java:3404)
	at com.redhat.ceylon.compiler.typechecker.tree.Walker.walkBody(Walker.java:413)
	at com.redhat.ceylon.compiler.typechecker.tree.Walker.walkBlock(Walker.java:418)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$Block.visitChildren(Tree.java:1754)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visitAny(Visitor.java:10)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:67)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:68)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$Block.visit(Tree.java:1746)
	at com.redhat.ceylon.compiler.typechecker.tree.CustomTree$MethodDefinition.visitChildren(CustomTree.java:160)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visitAny(Visitor.java:10)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:114)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:115)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:26)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:48)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:53)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:54)
	at com.redhat.ceylon.compiler.typechecker.analyzer.ExpressionVisitor.visit(ExpressionVisitor.java:1699)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$MethodDefinition.visit(Tree.java:1341)
	at com.redhat.ceylon.compiler.typechecker.tree.Walker.walkBody(Walker.java:413)
	at com.redhat.ceylon.compiler.typechecker.tree.Walker.walkClassBody(Walker.java:422)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$ClassBody.visitChildren(Tree.java:1782)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visitAny(Visitor.java:10)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:67)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:69)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$ClassBody.visit(Tree.java:1774)
	at com.redhat.ceylon.compiler.typechecker.tree.CustomTree$ClassDefinition.visitChildren(CustomTree.java:207)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visitAny(Visitor.java:10)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:114)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:115)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:26)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:28)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:29)
	at com.redhat.ceylon.compiler.typechecker.analyzer.ExpressionVisitor.visit(ExpressionVisitor.java:1759)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:40)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:41)
	at com.redhat.ceylon.compiler.typechecker.analyzer.ExpressionVisitor.visit(ExpressionVisitor.java:1751)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$ClassDefinition.visit(Tree.java:937)
	at com.redhat.ceylon.compiler.typechecker.tree.Walker.walkCompilationUnit(Walker.java:30)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$CompilationUnit.visitChildren(Tree.java:30)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visitAny(Visitor.java:10)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:12)
	at com.redhat.ceylon.compiler.typechecker.analyzer.ExpressionVisitor.visit(ExpressionVisitor.java:150)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$CompilationUnit.visit(Tree.java:22)
	at com.redhat.ceylon.compiler.typechecker.context.PhasedUnit.analyseTypes(PhasedUnit.java:338)
	at com.redhat.ceylon.compiler.typechecker.TypeChecker.executePhases(TypeChecker.java:164)
	at com.redhat.ceylon.compiler.typechecker.TypeChecker.process(TypeChecker.java:127)
	at com.redhat.ceylon.compiler.typechecker.TypeChecker.process(TypeChecker.java:122)
	at com.redhat.ceylon.ceylondoc.CeylonDocTool.initialize(CeylonDocTool.java:412)
	at com.redhat.ceylon.common.tool.ToolFactory$ArgumentProcessor.invokeInitialize(ToolFactory.java:381)
	at com.redhat.ceylon.common.tool.ToolFactory$ArgumentProcessor.processArguments(ToolFactory.java:261)
	at com.redhat.ceylon.common.tool.ToolFactory.bindArguments(ToolFactory.java:432)
	at com.redhat.ceylon.common.tool.ToolFactory.bindArguments(ToolFactory.java:137)
	at com.redhat.ceylon.common.tools.CeylonTool.getTool(CeylonTool.java:501)
	at com.redhat.ceylon.common.tools.CeylonTool.getTools(CeylonTool.java:479)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.redhat.ceylon.launcher.Launcher.runInJava7Checked(Launcher.java:89)
	at com.redhat.ceylon.launcher.Launcher.run(Launcher.java:40)
	at com.redhat.ceylon.launcher.Launcher.run(Launcher.java:33)
	at com.redhat.ceylon.launcher.Launcher.main(Launcher.java:26)
java.lang.NoSuchMethodException: com.sun.proxy.$Proxy41.reason()
	at java.lang.Class.getMethod(Class.java:1670)
	at com.redhat.ceylon.compiler.loader.impl.reflect.mirror.ReflectionAnnotation.getValue(ReflectionAnnotation.java:41)
	at com.redhat.ceylon.compiler.loader.LanguageAnnotation$6.makeFromCeylonAnnotation(LanguageAnnotation.java:86)
	at com.redhat.ceylon.compiler.loader.AbstractModelLoader.setAnnotations(AbstractModelLoader.java:2357)
	at com.redhat.ceylon.compiler.loader.AbstractModelLoader.addMethod(AbstractModelLoader.java:2525)
	at com.redhat.ceylon.compiler.loader.AbstractModelLoader.complete(AbstractModelLoader.java:2092)
	at com.redhat.ceylon.compiler.loader.AbstractModelLoader.complete(AbstractModelLoader.java:1901)
	at com.redhat.ceylon.compiler.loader.model.LazyInterface.load(LazyInterface.java:106)
	at com.redhat.ceylon.compiler.loader.model.LazyInterface.getExtendedTypeDeclaration(LazyInterface.java:177)
	at com.redhat.ceylon.compiler.typechecker.model.TypeDeclaration.getSupertypeDeclarations(TypeDeclaration.java:926)
	at com.redhat.ceylon.compiler.typechecker.model.Util.addToIntersection(Util.java:1019)
	at com.redhat.ceylon.compiler.typechecker.model.Util.addToIntersection(Util.java:984)
	at com.redhat.ceylon.compiler.typechecker.model.Util.intersectionType(Util.java:1434)
	at com.redhat.ceylon.compiler.typechecker.analyzer.ExpressionVisitor.narrow(ExpressionVisitor.java:727)
	at com.redhat.ceylon.compiler.typechecker.analyzer.ExpressionVisitor.visit(ExpressionVisitor.java:693)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$IsCondition.visit(Tree.java:4280)
	at com.redhat.ceylon.compiler.typechecker.tree.Walker.walkConditionList(Walker.java:985)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$ConditionList.visitChildren(Tree.java:4142)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visitAny(Visitor.java:10)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:158)
	at com.redhat.ceylon.compiler.typechecker.analyzer.ExpressionVisitor.visit(ExpressionVisitor.java:601)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$ConditionList.visit(Tree.java:4134)
	at com.redhat.ceylon.compiler.typechecker.tree.Walker.walkIfClause(Walker.java:798)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$IfClause.visitChildren(Tree.java:3441)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visitAny(Visitor.java:10)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:127)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:133)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$IfClause.visit(Tree.java:3433)
	at com.redhat.ceylon.compiler.typechecker.tree.Walker.walkIfStatement(Walker.java:790)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$IfStatement.visitChildren(Tree.java:3412)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visitAny(Visitor.java:10)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:114)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:115)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:117)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:126)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:132)
	at com.redhat.ceylon.compiler.typechecker.analyzer.ExpressionVisitor.visit(ExpressionVisitor.java:6731)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$IfStatement.visit(Tree.java:3404)
	at com.redhat.ceylon.compiler.typechecker.tree.Walker.walkBody(Walker.java:413)
	at com.redhat.ceylon.compiler.typechecker.tree.Walker.walkBlock(Walker.java:418)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$Block.visitChildren(Tree.java:1754)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visitAny(Visitor.java:10)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:67)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:68)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$Block.visit(Tree.java:1746)
	at com.redhat.ceylon.compiler.typechecker.tree.CustomTree$MethodDefinition.visitChildren(CustomTree.java:160)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visitAny(Visitor.java:10)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:114)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:115)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:26)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:48)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:53)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:54)
	at com.redhat.ceylon.compiler.typechecker.analyzer.ExpressionVisitor.visit(ExpressionVisitor.java:1699)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$MethodDefinition.visit(Tree.java:1341)
	at com.redhat.ceylon.compiler.typechecker.tree.Walker.walkBody(Walker.java:413)
	at com.redhat.ceylon.compiler.typechecker.tree.Walker.walkClassBody(Walker.java:422)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$ClassBody.visitChildren(Tree.java:1782)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visitAny(Visitor.java:10)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:67)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:69)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$ClassBody.visit(Tree.java:1774)
	at com.redhat.ceylon.compiler.typechecker.tree.CustomTree$ClassDefinition.visitChildren(CustomTree.java:207)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visitAny(Visitor.java:10)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:114)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:115)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:26)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:28)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:29)
	at com.redhat.ceylon.compiler.typechecker.analyzer.ExpressionVisitor.visit(ExpressionVisitor.java:1759)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:40)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:41)
	at com.redhat.ceylon.compiler.typechecker.analyzer.ExpressionVisitor.visit(ExpressionVisitor.java:1751)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$ClassDefinition.visit(Tree.java:937)
	at com.redhat.ceylon.compiler.typechecker.tree.Walker.walkCompilationUnit(Walker.java:30)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$CompilationUnit.visitChildren(Tree.java:30)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visitAny(Visitor.java:10)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:12)
	at com.redhat.ceylon.compiler.typechecker.analyzer.ExpressionVisitor.visit(ExpressionVisitor.java:150)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$CompilationUnit.visit(Tree.java:22)
	at com.redhat.ceylon.compiler.typechecker.context.PhasedUnit.analyseTypes(PhasedUnit.java:338)
	at com.redhat.ceylon.compiler.typechecker.TypeChecker.executePhases(TypeChecker.java:164)
	at com.redhat.ceylon.compiler.typechecker.TypeChecker.process(TypeChecker.java:127)
	at com.redhat.ceylon.compiler.typechecker.TypeChecker.process(TypeChecker.java:122)
	at com.redhat.ceylon.ceylondoc.CeylonDocTool.initialize(CeylonDocTool.java:412)
	at com.redhat.ceylon.common.tool.ToolFactory$ArgumentProcessor.invokeInitialize(ToolFactory.java:381)
	at com.redhat.ceylon.common.tool.ToolFactory$ArgumentProcessor.processArguments(ToolFactory.java:261)
	at com.redhat.ceylon.common.tool.ToolFactory.bindArguments(ToolFactory.java:432)
	at com.redhat.ceylon.common.tool.ToolFactory.bindArguments(ToolFactory.java:137)
	at com.redhat.ceylon.common.tools.CeylonTool.getTool(CeylonTool.java:501)
	at com.redhat.ceylon.common.tools.CeylonTool.getTools(CeylonTool.java:479)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.redhat.ceylon.launcher.Launcher.runInJava7Checked(Launcher.java:89)
	at com.redhat.ceylon.launcher.Launcher.run(Launcher.java:40)
	at com.redhat.ceylon.launcher.Launcher.run(Launcher.java:33)
	at com.redhat.ceylon.launcher.Launcher.main(Launcher.java:26)
Warning: Missing documentation for docbug(module.ceylon:1)
Warning: Missing documentation for docbug(package.ceylon:1)
Warning: Missing documentation for docbug::FileResourceLoader(run.ceylon:6)
```

**Comment by FroMage** [comment]
Fixed!
