### ISSUE TITLE
ceylon doc NPE w/new default constructors

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-compiler#2095]
This:

```ceylon
shared class C {
    shared new () {}
    shared new Named() {}
}
```

results in:

```
$ ceylon doc
Warning: Missing documentation for simple(module.ceylon:1)
Warning: Missing documentation for simple(package.ceylon:1)
Warning: Missing documentation for simple::C(run.ceylon:1)
ceylon doc: null
java.lang.NullPointerException
	at java.lang.String.compareTo(String.java:1142)
	at com.redhat.ceylon.ceylondoc.Util$ReferenceableComparatorByName.compare(Util.java:457)
	at com.redhat.ceylon.ceylondoc.Util$ReferenceableComparatorByName.compare(Util.java:451)
	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:351)
	at java.util.TimSort.sort(TimSort.java:216)
	at java.util.Arrays.sort(Arrays.java:1512)
	at java.util.ArrayList.sort(ArrayList.java:1454)
	at java.util.Collections.sort(Collections.java:175)
	at com.redhat.ceylon.ceylondoc.ClassDoc.loadMembers(ClassDoc.java:128)
	at com.redhat.ceylon.ceylondoc.ClassDoc.<init>(ClassDoc.java:91)
	at com.redhat.ceylon.ceylondoc.CeylonDocTool.doc(CeylonDocTool.java:982)
	at com.redhat.ceylon.ceylondoc.CeylonDocTool.doc(CeylonDocTool.java:873)
	at com.redhat.ceylon.ceylondoc.CeylonDocTool.documentModule(CeylonDocTool.java:647)
	at com.redhat.ceylon.ceylondoc.CeylonDocTool.makeDoc(CeylonDocTool.java:579)
	at com.redhat.ceylon.ceylondoc.CeylonDocTool.run(CeylonDocTool.java:555)
	at com.redhat.ceylon.common.tools.CeylonTool.run(CeylonTool.java:411)
	at com.redhat.ceylon.common.tools.CeylonTool.execute(CeylonTool.java:348)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.redhat.ceylon.launcher.Launcher.runInJava7Checked(Launcher.java:113)
	at com.redhat.ceylon.launcher.Launcher.run(Launcher.java:40)
	at com.redhat.ceylon.launcher.Launcher.run(Launcher.java:33)
	at com.redhat.ceylon.launcher.Launcher.main(Launcher.java:26)
```

With *just* the default constructor, the constructor is named `null` in the docs.

**Comment by thradec** [comment]
Done, thanks @jvasileff.
