### ISSUE TITLE
"ceylon compile --suppress-warning" throws

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-compiler#2117]
unless followed by `="..."`.

```shell
$ ceylon compile --suppress-warning
ceylon compile: Collection is empty
java.lang.IllegalArgumentException: Collection is empty
	at java.util.EnumSet.copyOf(EnumSet.java:166)
	at com.redhat.ceylon.common.tool.ToolFactory$ArgumentProcessor.setValue(ToolFactory.java:342)
	at com.redhat.ceylon.common.tool.ToolFactory$ArgumentProcessor.applyBindings(ToolFactory.java:360)
	at com.redhat.ceylon.common.tool.ToolFactory$ArgumentProcessor.processArguments(ToolFactory.java:258)
	at com.redhat.ceylon.common.tool.ToolFactory.bindArguments(ToolFactory.java:432)
	at com.redhat.ceylon.common.tool.ToolFactory.bindArguments(ToolFactory.java:137)
	at com.redhat.ceylon.common.tools.CeylonTool.getTool(CeylonTool.java:480)
	at com.redhat.ceylon.common.tools.CeylonTool.execute(CeylonTool.java:324)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.redhat.ceylon.launcher.Launcher.runInJava7Checked(Launcher.java:114)
	at com.redhat.ceylon.launcher.Launcher.run(Launcher.java:41)
	at com.redhat.ceylon.launcher.Launcher.run(Launcher.java:34)
	at com.redhat.ceylon.launcher.Launcher.main(Launcher.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.redhat.ceylon.launcher.Bootstrap.run(Bootstrap.java:50)
	at com.redhat.ceylon.launcher.Bootstrap.main(Bootstrap.java:30)
```

**Comment by FroMage** [comment]
Excellent, thanks!
