### ISSUE TITLE
Sequence Tuple trouble (StackOverflow)

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-compiler#2174]
With the recent `Tuple` work, I thought I'd finally submit this one that I've had for a while. AFAICT, the first issue below (2k iterations) has already been fixed.

```ceylon
shared void stackOverflowIsSequence() {
    variable [Integer*] seq = [];
    for (i in 0:5k) {
        seq = seq.withTrailing(i);
    }
    // seq is a giant tuple
    if (is [Integer*] s = (seq of Anything)) {}

    /*
        With 2k iterations:

        java.lang.RuntimeException: undecidable canonicalization
        at com.redhat.ceylon.compiler.typechecker.model.ProducedType.resolveAliases(ProducedType.java:2170)
        at com.redhat.ceylon.compiler.typechecker.model.ProducedType.curriedResolveAliases(ProducedType.java:2220)
        at com.redhat.ceylon.compiler.typechecker.model.ProducedType.resolveAliases(ProducedType.java:2174)
        at com.redhat.ceylon.compiler.typechecker.model.ProducedType.curriedResolveAliases(ProducedType.java:2220)
        at com.redhat.ceylon.compiler.typechecker.model.ProducedType.resolveAliases(ProducedType.java:2174)

        With 5k iterations:

        Caused by: java.lang.StackOverflowError
        at com.redhat.ceylon.compiler.java.runtime.model.TypeDescriptor$Nothing.hashCode(TypeDescriptor.java:458)
        at com.redhat.ceylon.compiler.java.runtime.model.TypeDescriptor.unorderedHashCode(TypeDescriptor.java:75)
        at com.redhat.ceylon.compiler.java.runtime.model.TypeDescriptor$Union.hashCode(TypeDescriptor.java:556)
        at java.util.Arrays.hashCode(Arrays.java:3140)
        at com.redhat.ceylon.compiler.java.runtime.model.TypeDescriptor$Class.hashCode(TypeDescriptor.java:182)
        at java.util.Arrays.hashCode(Arrays.java:3140)
        at com.redhat.ceylon.compiler.java.runtime.model.TypeDescriptor$Class.hashCode(TypeDescriptor.java:182)
        at java.util.Arrays.hashCode(Arrays.java:3140)
        at com.redhat.ceylon.compiler.java.runtime.model.TypeDescriptor$Class.hashCode(TypeDescriptor.java:182)
        at java.util.Arrays.hashCode(Arrays.java:3140)
    */
}
```

**Comment by gavinking** [comment]
@jvasileff I think this bug is misfiled. I'm guessing it's an issue for the language module runtime.

**Comment by jvasileff** [comment]
Oh, right. Moved to https://github.com/ceylon/ceylon.language/issues/702

**Comment by gavinking** [comment]
Thanks.

On Fri, May 29, 2015 at 2:56 PM, John Vasileff <notifications@github.com>
wrote:

> Oh, right. Moved to ceylon/ceylon.language#702
> <https://github.com/ceylon/ceylon.language/issues/702>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ceylon/ceylon-compiler/issues/2174#issuecomment-106796072>
> .
>



-- 
Gavin King
gavin@ceylon-lang.org
http://profiles.google.com/gavin.king
http://ceylon-lang.org
http://hibernate.org
http://seamframework.org
