### ISSUE TITLE
optimize @TypeInfo for homogeneous tuple types

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-compiler#2188]
Given this code:

```ceylon
Null[1k] null = nothing;
```

I get:

```
java.lang.StackOverflowError
	at com.redhat.ceylon.model.typechecker.util.TypePrinter.getSimpleDeclarationName(TypePrinter.java:669)
	at com.redhat.ceylon.model.typechecker.util.TypePrinter.printDeclaration(TypePrinter.java:664)
	at com.redhat.ceylon.model.typechecker.util.TypePrinter.getSimpleProducedTypeName(TypePrinter.java:594)
	at com.redhat.ceylon.model.typechecker.util.TypePrinter.print(TypePrinter.java:322)
	at com.redhat.ceylon.model.typechecker.util.TypePrinter.getSimpleProducedTypeName(TypePrinter.java:624)
	at com.redhat.ceylon.model.typechecker.util.TypePrinter.print(TypePrinter.java:322)
	at com.redhat.ceylon.model.typechecker.util.TypePrinter.getSimpleProducedTypeName(TypePrinter.java:624)
	at com.redhat.ceylon.model.typechecker.util.TypePrinter.print(TypePrinter.java:322)
	at com.redhat.ceylon.model.typechecker.util.TypePrinter.getSimpleProducedTypeName(TypePrinter.java:624)
	at com.redhat.ceylon.model.typechecker.util.TypePrinter.print(TypePrinter.java:322)
	at com.redhat.ceylon.model.typechecker.util.TypePrinter.getSimpleProducedTypeName(TypePrinter.java:624)
	at com.redhat.ceylon.model.typechecker.util.TypePrinter.print(TypePrinter.java:322)
	at com.redhat.ceylon.model.typechecker.util.TypePrinter.getSimpleProducedTypeName(TypePrinter.java:624)
	at com.redhat.ceylon.model.typechecker.util.TypePrinter.print(TypePrinter.java:322)
	at com.redhat.ceylon.model.typechecker.util.TypePrinter.getSimpleProducedTypeName(TypePrinter.java:624)
	at com.redhat.ceylon.model.typechecker.util.TypePrinter.print(TypePrinter.java:322)
	at com.redhat.ceylon.model.typechecker.util.TypePrinter.getSimpleProducedTypeName(TypePrinter.java:624)
	at com.redhat.ceylon.model.typechecker.util.TypePrinter.print(TypePrinter.java:322)
	at com.redhat.ceylon.model.typechecker.util.TypePrinter.getSimpleProducedTypeName(TypePrinter.java:624)
	at com.redhat.ceylon.model.typechecker.util.TypePrinter.print(TypePrinter.java:322)
	at com.redhat.ceylon.model.typechecker.util.TypePrinter.getSimpleProducedTypeName(TypePrinter.java:624)
	at com.redhat.ceylon.model.typechecker.util.TypePrinter.print(TypePrinter.java:322)
	at com.redhat.ceylon.model.typechecker.util.TypePrinter.getSimpleProducedTypeName(TypePrinter.java:624)
	at com.redhat.ceylon.model.typechecker.util.TypePrinter.print(TypePrinter.java:322)
	at com.redhat.ceylon.model.typechecker.util.TypePrinter.getSimpleProducedTypeName(TypePrinter.java:624)
	at com.redhat.ceylon.model.typechecker.util.TypePrinter.print(TypePrinter.java:322)
	at com.redhat.ceylon.model.typechecker.util.TypePrinter.getSimpleProducedTypeName(TypePrinter.java:624)
	at com.redhat.ceylon.model.typechecker.util.TypePrinter.print(TypePrinter.java:322)
	at com.redhat.ceylon.model.typechecker.util.TypePrinter.getSimpleProducedTypeName(TypePrinter.java:624)
	at com.redhat.ceylon.model.typechecker.util.TypePrinter.print(TypePrinter.java:322)
	at com.redhat.ceylon.model.typechecker.util.TypePrinter.getSimpleProducedTypeName(TypePrinter.java:624)
	at com.redhat.ceylon.model.typechecker.util.TypePrinter.print(TypePrinter.java:322)
	at com.redhat.ceylon.model.typechecker.util.TypePrinter.getSimpleProducedTypeName(TypePrinter.java:624)
```

That's because `getSimpleProducedTypeName()` uses a _very_ inefficient format to store tuple types, especially homogeneous tuple types like this one. It should use something much more efficient.

**Comment by tombentley** [comment]
To be honest I think we should also optimize other Tuple types at the same time, because for tuples of more than length 2 they can be pretty massive too.

At which point I do start to wonder if the type parser should just support all the same abbreviations that the language supports.

**Comment by gavinking** [comment]
@tombentley +1

**Comment by tombentley** [comment]
I have:

* Added support for all the spec'd type abbreviations to the `TypeParser`,
* Changed the `TypePrinter` so it uses type abbreviations and
* Made the `TypeLexer` ignore whitespace, since the `TypePrinter` likes to add them.

So hand written `@TypeInfo` should now be easier to write, and this issue is resolved.

**Comment by gavinking** [comment]
Fantastic!
