### ISSUE TITLE
issues with non-captured `late` value initialization

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-compiler#2194]
Non-captured `late` references may not make sense, but these appear to be bugs nevertheless:

1. No `InitializationError` on second initialization. And this actually runs, despite the generated Java code declaring `s` `final`:

```ceylon
shared class TC() {
  late String s;
  s = "s";
  s = "t";
  print(s);
}
```

2. The following fails in eclipse with `Exception in thread "main" java.lang.VerifyError: Bad local variable type` but I wasn't able to reproduce using the CLI:

```ceylon
shared class TC() {
  late String s;
  for (_ in 1..1) {
    s = "s";
  }
  print(s);
}
```

**Comment by jvasileff** [comment]
Oh, actually the second scenario can be reproduced on the CLI. I just forgot to run it!

```
$ ceylon run --run=simple::TC simple
Exception in thread "main" java.lang.VerifyError: Bad local variable type
Exception Details:
  Location:
    simple/TC.<init>()V @86: aload_1
  Reason:
    Type top (current frame, locals[1]) is not assignable to reference type
  Current Frame:
    bci: @86
    flags: { }
    locals: { 'simple/TC', top, long, long_2nd, long, long_2nd, integer, long, long_2nd }
    stack: { }
  Bytecode:
    0x0000000: 2ab7 0001 0a41 0a37 040a 0ab8 0002 0994
    0x0000010: 9b00 0704 a700 0403 3606 1506 9900 070a
    0x0000020: a700 0614 0003 3707 0a37 0915 0699 000f
    0x0000030: 1609 0a65 0994 9d00 20a7 000c 1609 0a65
    0x0000040: 0994 9b00 1416 0937 0b12 054c 1609 1607
    0x0000050: 6137 09a7 ffd8 2bb8 0006 b800 07b1     
  Stackmap Table:
    full_frame(@23,{Object[#39],Top,Long,Long},{})
    same_locals_1_stack_item_frame(@24,Integer)
    append_frame(@35,Integer)
    same_locals_1_stack_item_frame(@38,Long)
    append_frame(@43,Long,Long)
    same_frame(@60)
    same_frame(@69)
    chop_frame(@86,1)

	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.getDeclaredMethod(Class.java:2128)
	at ceylon.modules.api.runtime.SecurityActions.invokeRunInternal(SecurityActions.java:54)
	at ceylon.modules.api.runtime.SecurityActions.invokeRun(SecurityActions.java:48)
	at ceylon.modules.api.runtime.AbstractRuntime.invokeRun(AbstractRuntime.java:110)
	at ceylon.modules.api.runtime.AbstractRuntime.execute(AbstractRuntime.java:176)
	at ceylon.modules.api.runtime.AbstractRuntime.execute(AbstractRuntime.java:160)
	at ceylon.modules.Main.execute(Main.java:69)
	at ceylon.modules.Main.main(Main.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.jboss.modules.Module.run(Module.java:312)
	at org.jboss.modules.Main.main(Main.java:460)
	at ceylon.modules.bootstrap.CeylonRunTool.run(CeylonRunTool.java:245)
	at com.redhat.ceylon.common.tools.CeylonTool.run(CeylonTool.java:390)
	at com.redhat.ceylon.common.tools.CeylonTool.execute(CeylonTool.java:327)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.redhat.ceylon.launcher.Launcher.runInJava7Checked(Launcher.java:114)
	at com.redhat.ceylon.launcher.Launcher.run(Launcher.java:41)
	at com.redhat.ceylon.launcher.Launcher.run(Launcher.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.redhat.ceylon.launcher.Bootstrap.run(Bootstrap.java:55)
	at com.redhat.ceylon.launcher.Bootstrap.main(Bootstrap.java:32)
```

**Comment by FroMage** [comment]
Moving to 1.3.
