### ISSUE TITLE
Error taking when reference to shared function

### ISSUE THREAD

**Issue by Eroc33** [ceylon/ceylon-compiler#2197]
The compiler (version 1.1.0) errors with the following stacktrace:
````
com.redhat.ceylon.compiler.CompilerBugException: Bug
        at com.redhat.ceylon.compiler.CeylonCompileTool.handleExitCode(CeylonCompileTool.java:472)
        at com.redhat.ceylon.compiler.CeylonCompileTool.run(CeylonCompileTool.java:454)
        at com.redhat.ceylon.common.tools.CeylonTool.run(CeylonTool.java:352)
        at com.redhat.ceylon.common.tools.CeylonTool.execute(CeylonTool.java:291)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at com.redhat.ceylon.launcher.Launcher.runInJava7Checked(Launcher.java:104)
        at com.redhat.ceylon.launcher.Launcher.run(Launcher.java:37)
        at com.redhat.ceylon.launcher.Launcher.run(Launcher.java:30)
        at com.redhat.ceylon.launcher.Launcher.main(Launcher.java:23)
Caused by: java.lang.RuntimeException: Error generating bytecode for source\uk\me\rochester\bug_mvce\run.ceylon
        at com.redhat.ceylon.compiler.java.tools.LanguageCompiler.genCodeUnlessError(LanguageCompiler.java:765)
        at com.redhat.ceylon.compiler.java.tools.LanguageCompiler.genCode(LanguageCompiler.java:705)
        at com.sun.tools.javac.main.JavaCompiler.generate(JavaCompiler.java:1450)
        at com.redhat.ceylon.compiler.java.tools.LanguageCompiler.generate(LanguageCompiler.java:816)
        at com.sun.tools.javac.main.JavaCompiler.generate(JavaCompiler.java:1418)
        at com.sun.tools.javac.main.JavaCompiler.compile2(JavaCompiler.java:871)
        at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:829)
        at com.redhat.ceylon.compiler.java.tools.LanguageCompiler.compile(LanguageCompiler.java:227)
        at com.redhat.ceylon.compiler.java.launcher.Main.compile(Main.java:650)
        at com.redhat.ceylon.compiler.java.launcher.Main.compile(Main.java:566)
        at com.redhat.ceylon.compiler.java.launcher.Main.compile(Main.java:556)
        at com.redhat.ceylon.compiler.CeylonCompileTool.run(CeylonCompileTool.java:453)
        ... 10 more
Caused by: java.lang.AssertionError
        at com.sun.tools.javac.jvm.Items$Item.load(Items.java:207)
        at com.sun.tools.javac.jvm.Items$Item.coerce(Items.java:251)
        at com.sun.tools.javac.jvm.Items$Item.coerce(Items.java:270)
        at com.sun.tools.javac.jvm.Gen.genExpr(Gen.java:839)
        at com.sun.tools.javac.jvm.Gen.visitTypeCast(Gen.java:2067)
        at com.sun.tools.javac.tree.JCTree$JCTypeCast.accept(JCTree.java:1596)
        at com.sun.tools.javac.jvm.Gen.genExpr(Gen.java:837)
        at com.sun.tools.javac.jvm.Gen.visitReturn(Gen.java:1659)
        at com.sun.tools.javac.tree.JCTree$JCReturn.accept(JCTree.java:1242)
        at com.sun.tools.javac.jvm.Gen.genDef(Gen.java:684)
        at com.sun.tools.javac.jvm.Gen.genStat(Gen.java:719)
        at com.sun.tools.javac.jvm.Gen.genStat(Gen.java:705)
        at com.sun.tools.javac.jvm.Gen.genStats(Gen.java:756)
        at com.sun.tools.javac.jvm.Gen.visitBlock(Gen.java:1031)
        at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:783)
        at com.sun.tools.javac.jvm.Gen.genDef(Gen.java:684)
        at com.sun.tools.javac.jvm.Gen.genStat(Gen.java:719)
        at com.sun.tools.javac.jvm.Gen.genMethod(Gen.java:912)
        at com.sun.tools.javac.jvm.Gen.visitMethodDef(Gen.java:885)
        at com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:671)
        at com.sun.tools.javac.jvm.Gen.genDef(Gen.java:684)
        at com.sun.tools.javac.jvm.Gen.genClass(Gen.java:2246)
        at com.redhat.ceylon.compiler.java.tools.LanguageCompiler.genCodeUnlessError(LanguageCompiler.java:736)
        ... 21 more
````
when compiling the following code:
````
import ceylon.net.http.server { ... }

"Run the module `uk.me.rochester.bug_mvce`."
shared void run() {
	value a = Endpoint{
		path = isRoot();
		service = (Request req, Response res)=>null;
	};
	value b = a.service;
}
````

**Comment by quintesse** [comment]
In the current compiler there is still an error but now it is simply:

```
error: incompatible types
  required: Object
  found:    void
```

But I'm wondering: why this doesn't generate the typical "this is probably a compiler bug, please report this yadda yadda" message anymore? @FroMage @tombentley ?

**Comment by sgalles** [comment]
same error with
```ceylon
Anything a = "".copyTo;
```

**Comment by quintesse** [comment]
@tombentley any comment on the missing error message on the console?

**Comment by tombentley** [comment]
Open a different issue about that please.
