### ISSUE TITLE
javac crash with switch expression as constructor argument

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-compiler#2219]
This:

```ceylon
"Run the module `simple`."
shared void run() {
    Integer|Float foo = 1;
    String s = String(
        switch (foo)
        case (is Integer) "integer"
        case (is Float) "float");
}
```

results in this (with the stack trace duplicated):
```
$ ceylon compile simple
warning: It looks like you are using class files from a Java newer than 1.7.
  Everything should work well, but if not, let us know at https://github.com/ceylon/ceylon-compiler/issues.
  In the near future, the Ceylon compiler will be upgraded to handle Java 1.8.
source/simple/run.ceylon:4: warning: declaration is never used: 's'
    String s = String(
           ^
An exception has occurred in the compiler (ceylonc 1.1.1 (Pif Gadget)).
java.lang.RuntimeException: Error generating bytecode for source/simple/run.ceylon
	at com.redhat.ceylon.compiler.java.tools.LanguageCompiler.genCodeUnlessError(LanguageCompiler.java:839)
	at com.redhat.ceylon.compiler.java.tools.LanguageCompiler.genCode(LanguageCompiler.java:779)
	at com.sun.tools.javac.main.JavaCompiler.generate(JavaCompiler.java:1450)
	at com.redhat.ceylon.compiler.java.tools.LanguageCompiler.generate(LanguageCompiler.java:890)
	at com.sun.tools.javac.main.JavaCompiler.generate(JavaCompiler.java:1418)
	at com.sun.tools.javac.main.JavaCompiler.compile2(JavaCompiler.java:871)
	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:829)
	at com.redhat.ceylon.compiler.java.tools.LanguageCompiler.compile(LanguageCompiler.java:245)
	at com.redhat.ceylon.compiler.java.launcher.Main.compile(Main.java:650)
	at com.redhat.ceylon.compiler.java.launcher.Main.compile(Main.java:566)
	at com.redhat.ceylon.compiler.java.launcher.Main.compile(Main.java:556)
	at com.redhat.ceylon.compiler.CeylonCompileTool.run(CeylonCompileTool.java:503)
	at com.redhat.ceylon.common.tools.CeylonTool.run(CeylonTool.java:390)
	at com.redhat.ceylon.common.tools.CeylonTool.execute(CeylonTool.java:327)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.redhat.ceylon.launcher.Launcher.runInJava7Checked(Launcher.java:114)
	at com.redhat.ceylon.launcher.Launcher.run(Launcher.java:41)
	at com.redhat.ceylon.launcher.Launcher.run(Launcher.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.redhat.ceylon.launcher.Bootstrap.run(Bootstrap.java:55)
	at com.redhat.ceylon.launcher.Bootstrap.main(Bootstrap.java:32)
Caused by: java.lang.AssertionError
	at com.sun.tools.javac.util.Assert.error(Assert.java:126)
	at com.sun.tools.javac.util.Assert.check(Assert.java:45)
	at com.sun.tools.javac.jvm.Code.postop(Code.java:375)
	at com.sun.tools.javac.jvm.Code.emitop0(Code.java:875)
	at com.sun.tools.javac.jvm.Gen.visitThrow(Gen.java:1676)
	at com.sun.tools.javac.tree.JCTree$JCThrow.accept(JCTree.java:1265)
	at com.sun.tools.javac.jvm.Gen.genDef(Gen.java:683)
	at com.sun.tools.javac.jvm.Gen.genStat(Gen.java:718)
	at com.sun.tools.javac.jvm.Gen.genStat(Gen.java:704)
	at com.sun.tools.javac.jvm.Gen.visitIf(Gen.java:1620)
	at com.sun.tools.javac.tree.JCTree$JCIf.accept(JCTree.java:1142)
	at com.sun.tools.javac.jvm.Gen.genDef(Gen.java:683)
	at com.sun.tools.javac.jvm.Gen.genStat(Gen.java:718)
	at com.sun.tools.javac.jvm.Gen.genStat(Gen.java:704)
	at com.sun.tools.javac.jvm.Gen.visitIf(Gen.java:1620)
	at com.sun.tools.javac.tree.JCTree$JCIf.accept(JCTree.java:1142)
	at com.sun.tools.javac.jvm.Gen.genDef(Gen.java:683)
	at com.sun.tools.javac.jvm.Gen.genStat(Gen.java:718)
	at com.sun.tools.javac.jvm.Gen.genStat(Gen.java:704)
	at com.sun.tools.javac.jvm.Gen.genStats(Gen.java:755)
	at com.sun.tools.javac.jvm.Gen.visitBlock(Gen.java:1030)
	at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:783)
	at com.sun.tools.javac.jvm.Gen.genDef(Gen.java:683)
	at com.sun.tools.javac.jvm.Gen.genStat(Gen.java:718)
	at com.sun.tools.javac.jvm.Gen.genStat(Gen.java:704)
	at com.sun.tools.javac.jvm.Gen.genStats(Gen.java:755)
	at com.sun.tools.javac.jvm.Gen.visitLetExpr(Gen.java:2209)
	at com.sun.tools.javac.tree.JCTree$LetExpr.accept(JCTree.java:2114)
	at com.sun.tools.javac.jvm.Gen.genExpr(Gen.java:836)
	at com.sun.tools.javac.jvm.Gen.genArgs(Gen.java:855)
	at com.sun.tools.javac.jvm.Gen.visitApply(Gen.java:1690)
	at com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1323)
	at com.sun.tools.javac.jvm.Gen.genExpr(Gen.java:836)
	at com.sun.tools.javac.jvm.Gen.genArgs(Gen.java:855)
	at com.sun.tools.javac.jvm.Gen.visitNewClass(Gen.java:1731)
	at com.sun.tools.javac.tree.JCTree$JCNewClass.accept(JCTree.java:1374)
	at com.sun.tools.javac.jvm.Gen.genExpr(Gen.java:836)
	at com.sun.tools.javac.jvm.Gen.visitSelect(Gen.java:2144)
	at com.sun.tools.javac.tree.JCTree$JCFieldAccess.accept(JCTree.java:1679)
	at com.sun.tools.javac.jvm.Gen.genExpr(Gen.java:836)
	at com.sun.tools.javac.jvm.Gen.visitApply(Gen.java:1686)
	at com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1323)
	at com.sun.tools.javac.jvm.Gen.genExpr(Gen.java:836)
	at com.sun.tools.javac.jvm.Gen.visitVarDef(Gen.java:1017)
	at com.sun.tools.javac.tree.JCTree$JCVariableDecl.accept(JCTree.java:727)
	at com.sun.tools.javac.jvm.Gen.genDef(Gen.java:683)
	at com.sun.tools.javac.jvm.Gen.genStat(Gen.java:718)
	at com.sun.tools.javac.jvm.Gen.genStat(Gen.java:704)
	at com.sun.tools.javac.jvm.Gen.genStats(Gen.java:755)
	at com.sun.tools.javac.jvm.Gen.visitBlock(Gen.java:1030)
	at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:783)
	at com.sun.tools.javac.jvm.Gen.genDef(Gen.java:683)
	at com.sun.tools.javac.jvm.Gen.genStat(Gen.java:718)
	at com.sun.tools.javac.jvm.Gen.genMethod(Gen.java:911)
	at com.sun.tools.javac.jvm.Gen.visitMethodDef(Gen.java:884)
	at com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:671)
	at com.sun.tools.javac.jvm.Gen.genDef(Gen.java:683)
	at com.sun.tools.javac.jvm.Gen.genClass(Gen.java:2246)
	at com.redhat.ceylon.compiler.java.tools.LanguageCompiler.genCodeUnlessError(LanguageCompiler.java:810)
	... 26 more
ceylon compile: Fatal error: The compiler exited abnormally (4) due to a bug in
the compiler.
Please report it:
 https://github.com/ceylon/ceylon-compiler/issues/new
Please include:

* the stacktrace printed below
* a description of what you were trying to compile.

Thank you!
com.redhat.ceylon.compiler.CompilerBugException: Bug
	at com.redhat.ceylon.compiler.CeylonCompileTool.handleExitCode(CeylonCompileTool.java:522)
	at com.redhat.ceylon.compiler.CeylonCompileTool.run(CeylonCompileTool.java:504)
	at com.redhat.ceylon.common.tools.CeylonTool.run(CeylonTool.java:390)
	at com.redhat.ceylon.common.tools.CeylonTool.execute(CeylonTool.java:327)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.redhat.ceylon.launcher.Launcher.runInJava7Checked(Launcher.java:114)
	at com.redhat.ceylon.launcher.Launcher.run(Launcher.java:41)
	at com.redhat.ceylon.launcher.Launcher.run(Launcher.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.redhat.ceylon.launcher.Bootstrap.run(Bootstrap.java:55)
	at com.redhat.ceylon.launcher.Bootstrap.main(Bootstrap.java:32)
Caused by: java.lang.RuntimeException: Error generating bytecode for source/simple/run.ceylon
	at com.redhat.ceylon.compiler.java.tools.LanguageCompiler.genCodeUnlessError(LanguageCompiler.java:839)
	at com.redhat.ceylon.compiler.java.tools.LanguageCompiler.genCode(LanguageCompiler.java:779)
	at com.sun.tools.javac.main.JavaCompiler.generate(JavaCompiler.java:1450)
	at com.redhat.ceylon.compiler.java.tools.LanguageCompiler.generate(LanguageCompiler.java:890)
	at com.sun.tools.javac.main.JavaCompiler.generate(JavaCompiler.java:1418)
	at com.sun.tools.javac.main.JavaCompiler.compile2(JavaCompiler.java:871)
	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:829)
	at com.redhat.ceylon.compiler.java.tools.LanguageCompiler.compile(LanguageCompiler.java:245)
	at com.redhat.ceylon.compiler.java.launcher.Main.compile(Main.java:650)
	at com.redhat.ceylon.compiler.java.launcher.Main.compile(Main.java:566)
	at com.redhat.ceylon.compiler.java.launcher.Main.compile(Main.java:556)
	at com.redhat.ceylon.compiler.CeylonCompileTool.run(CeylonCompileTool.java:503)
	... 15 more
Caused by: java.lang.AssertionError
	at com.sun.tools.javac.util.Assert.error(Assert.java:126)
	at com.sun.tools.javac.util.Assert.check(Assert.java:45)
	at com.sun.tools.javac.jvm.Code.postop(Code.java:375)
	at com.sun.tools.javac.jvm.Code.emitop0(Code.java:875)
	at com.sun.tools.javac.jvm.Gen.visitThrow(Gen.java:1676)
	at com.sun.tools.javac.tree.JCTree$JCThrow.accept(JCTree.java:1265)
	at com.sun.tools.javac.jvm.Gen.genDef(Gen.java:683)
	at com.sun.tools.javac.jvm.Gen.genStat(Gen.java:718)
	at com.sun.tools.javac.jvm.Gen.genStat(Gen.java:704)
	at com.sun.tools.javac.jvm.Gen.visitIf(Gen.java:1620)
	at com.sun.tools.javac.tree.JCTree$JCIf.accept(JCTree.java:1142)
	at com.sun.tools.javac.jvm.Gen.genDef(Gen.java:683)
	at com.sun.tools.javac.jvm.Gen.genStat(Gen.java:718)
	at com.sun.tools.javac.jvm.Gen.genStat(Gen.java:704)
	at com.sun.tools.javac.jvm.Gen.visitIf(Gen.java:1620)
	at com.sun.tools.javac.tree.JCTree$JCIf.accept(JCTree.java:1142)
	at com.sun.tools.javac.jvm.Gen.genDef(Gen.java:683)
	at com.sun.tools.javac.jvm.Gen.genStat(Gen.java:718)
	at com.sun.tools.javac.jvm.Gen.genStat(Gen.java:704)
	at com.sun.tools.javac.jvm.Gen.genStats(Gen.java:755)
	at com.sun.tools.javac.jvm.Gen.visitBlock(Gen.java:1030)
	at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:783)
	at com.sun.tools.javac.jvm.Gen.genDef(Gen.java:683)
	at com.sun.tools.javac.jvm.Gen.genStat(Gen.java:718)
	at com.sun.tools.javac.jvm.Gen.genStat(Gen.java:704)
	at com.sun.tools.javac.jvm.Gen.genStats(Gen.java:755)
	at com.sun.tools.javac.jvm.Gen.visitLetExpr(Gen.java:2209)
	at com.sun.tools.javac.tree.JCTree$LetExpr.accept(JCTree.java:2114)
	at com.sun.tools.javac.jvm.Gen.genExpr(Gen.java:836)
	at com.sun.tools.javac.jvm.Gen.genArgs(Gen.java:855)
	at com.sun.tools.javac.jvm.Gen.visitApply(Gen.java:1690)
	at com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1323)
	at com.sun.tools.javac.jvm.Gen.genExpr(Gen.java:836)
	at com.sun.tools.javac.jvm.Gen.genArgs(Gen.java:855)
	at com.sun.tools.javac.jvm.Gen.visitNewClass(Gen.java:1731)
	at com.sun.tools.javac.tree.JCTree$JCNewClass.accept(JCTree.java:1374)
	at com.sun.tools.javac.jvm.Gen.genExpr(Gen.java:836)
	at com.sun.tools.javac.jvm.Gen.visitSelect(Gen.java:2144)
	at com.sun.tools.javac.tree.JCTree$JCFieldAccess.accept(JCTree.java:1679)
	at com.sun.tools.javac.jvm.Gen.genExpr(Gen.java:836)
	at com.sun.tools.javac.jvm.Gen.visitApply(Gen.java:1686)
	at com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1323)
	at com.sun.tools.javac.jvm.Gen.genExpr(Gen.java:836)
	at com.sun.tools.javac.jvm.Gen.visitVarDef(Gen.java:1017)
	at com.sun.tools.javac.tree.JCTree$JCVariableDecl.accept(JCTree.java:727)
	at com.sun.tools.javac.jvm.Gen.genDef(Gen.java:683)
	at com.sun.tools.javac.jvm.Gen.genStat(Gen.java:718)
	at com.sun.tools.javac.jvm.Gen.genStat(Gen.java:704)
	at com.sun.tools.javac.jvm.Gen.genStats(Gen.java:755)
	at com.sun.tools.javac.jvm.Gen.visitBlock(Gen.java:1030)
	at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:783)
	at com.sun.tools.javac.jvm.Gen.genDef(Gen.java:683)
	at com.sun.tools.javac.jvm.Gen.genStat(Gen.java:718)
	at com.sun.tools.javac.jvm.Gen.genMethod(Gen.java:911)
	at com.sun.tools.javac.jvm.Gen.visitMethodDef(Gen.java:884)
	at com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:671)
	at com.sun.tools.javac.jvm.Gen.genDef(Gen.java:683)
	at com.sun.tools.javac.jvm.Gen.genClass(Gen.java:2246)
	at com.redhat.ceylon.compiler.java.tools.LanguageCompiler.genCodeUnlessError(LanguageCompiler.java:810)
	... 26 more
```

**Comment by tombentley** [comment]
The problem here is the use of an exhaustive `switch`: The compiler emits an extra `else` which throws to cover the possibility that recompilation has broken the exhaustivity and also to appease javacs flow analysis. If you use a non-exhaustive switch the problem goes away.

In Java you can only use `throw` as a statement, and that exits the current method. So the operand stack is expected to be empty after a `throw`. But here (because we're instantiating) the `new` instruction has pushed an uninitialized `this` on to the operand stack, so the stack is not empty after the `athrow` instruction has been emitted.

The problem is therefore also exhibited with normal methods because those push the receiver onto the stack, but not top level functions which are dispatched with `invokestatic` (without a receiver).

**Comment by FroMage** [comment]
Seriously impressed by your fix, man ;)

**Comment by tombentley** [comment]
It came after a morning of thinking hard about it, but it was pretty simple in the end.
