### ISSUE TITLE
IOOB trying to print type of value constructor instance

### ISSUE THREAD

**Issue by sgalles** [ceylon/ceylon-compiler#2238]
This code
```ceylon
import ceylon.language.meta {
	type
}

class Foo {
	shared new foo{}
}

shared void run(){
	print(type(Foo.foo));
}
```
executed
```
ceylon run: Index: 0, Size: 0
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.MethodHandleUtil.unboxArguments(MethodHandleUtil.java:94)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.MethodHandleUtil.unboxArguments(MethodHandleUtil.java:81)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.AppliedClass.reflectionToMethodHandle(AppliedClass.java:267)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.AppliedClass.initConstructor(AppliedClass.java:192)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.AppliedClass.init(AppliedClass.java:87)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.AppliedClassOrInterface.checkInit(AppliedClassOrInterface.java:73)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.AppliedClassOrInterface.getTypeArguments(AppliedClassOrInterface.java:104)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.toTypeString(Metamodel.java:1388)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.AppliedClassOrInterface.toString(AppliedClassOrInterface.java:1151)
	at ceylon.language.stringify_.stringify(print.ceylon:36)
	at ceylon.language.print_.print(print.ceylon:13)
```

**Comment by FroMage** [comment]
I can't fix this until the metamodel supports constructors.
