### ISSUE TITLE
Encode error building ceylon on Windows (8.1)

### ISSUE THREAD

**Issue by DiegoCoronel** [ceylon/ceylon-compiler#2254]
```
[ceylon-p2] Category module-bundles found
[ceylon-p2] Category only-dependencies-bundles found
[ceylon-p2] Generating artifacts.xml
[ceylon-p2] ceylon p2: Underlying stream encoding 'Cp1252' and input paramter fo
r
[ceylon-p2] writeStartDocument() method 'UTF-8' do not match.
[ceylon-p2] javax.xml.stream.XMLStreamException: Underlying stream encoding 'Cp1
252' and input paramter for writeStartDocument() method 'UTF-8' do not match.
[ceylon-p2]     at com.sun.xml.internal.stream.writers.XMLStreamWriterImpl.write
StartDocument(XMLStreamWriterImpl.java:1191)
[ceylon-p2]     at com.redhat.ceylon.tools.p2.IndentingWriter.writeStartDocument
(IndentingWriter.java:193)
[ceylon-p2]     at com.redhat.ceylon.tools.p2.CeylonP2Tool.printArtifacts(Ceylon
P2Tool.java:748)
[ceylon-p2]     at com.redhat.ceylon.tools.p2.CeylonP2Tool.run(CeylonP2Tool.java
:132)
[ceylon-p2]     at com.redhat.ceylon.common.tools.CeylonTool.run(CeylonTool.java
:390)
[ceylon-p2]     at com.redhat.ceylon.common.tools.CeylonTool.execute(CeylonTool.
java:327)
[ceylon-p2]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ceylon-p2]     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAcces
sorImpl.java:62)
[ceylon-p2]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMet
hodAccessorImpl.java:43)
[ceylon-p2]     at java.lang.reflect.Method.invoke(Method.java:497)
[ceylon-p2]     at com.redhat.ceylon.launcher.Launcher.runInJava7Checked(Launche
r.java:114)
[ceylon-p2]     at com.redhat.ceylon.ant.CeylonAntTask.executeCommandline(Ceylon
AntTask.java:216)
[ceylon-p2]     at com.redhat.ceylon.ant.CeylonAntTask.execute(CeylonAntTask.jav
a:173)
```

**Comment by FroMage** [comment]
Done, can you confirm that it works for you now please?

**Comment by DiegoCoronel** [comment]
yes, tks

**Comment by FroMage** [comment]
Great, thanks!
