### ISSUE TITLE
Can't assign the result of a switch to a variable member

### ISSUE THREAD

**Issue by bjansen** [ceylon/ceylon-compiler#2265]
The following code cannot be compiled to bytecode:

```ceylon
class Test() {
    variable String? foo = null;
    
    void myFunction(String param) {
        foo = switch(param)
        case ("foo") "foo"
        else "not foo";
    }
}
```

```
com.redhat.ceylon.compiler.CompilerBugException: Bug
	at com.redhat.ceylon.compiler.CeylonCompileTool.handleExitCode(CeylonCompileTool.java:522)
	at com.redhat.ceylon.compiler.CeylonCompileTool.run(CeylonCompileTool.java:504)
	at com.redhat.ceylon.common.tools.CeylonTool.run(CeylonTool.java:390)
	at com.redhat.ceylon.common.tools.CeylonTool.execute(CeylonTool.java:327)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.redhat.ceylon.launcher.Launcher.runInJava7Checked(Launcher.java:114)
	at com.redhat.ceylon.launcher.Launcher.run(Launcher.java:41)
	at com.redhat.ceylon.launcher.Launcher.run(Launcher.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.redhat.ceylon.launcher.Bootstrap.run(Bootstrap.java:55)
	at com.redhat.ceylon.launcher.Bootstrap.main(Bootstrap.java:32)
Caused by: java.lang.RuntimeException: Error generating bytecode for source/myothermodule/test.ceylon
	at com.redhat.ceylon.compiler.java.tools.LanguageCompiler.genCodeUnlessError(LanguageCompiler.java:839)
	at com.redhat.ceylon.compiler.java.tools.LanguageCompiler.genCode(LanguageCompiler.java:779)
	at com.sun.tools.javac.main.JavaCompiler.generate(JavaCompiler.java:1450)
	at com.redhat.ceylon.compiler.java.tools.LanguageCompiler.generate(LanguageCompiler.java:890)
	at com.sun.tools.javac.main.JavaCompiler.generate(JavaCompiler.java:1418)
	at com.sun.tools.javac.main.JavaCompiler.compile2(JavaCompiler.java:871)
	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:829)
	at com.redhat.ceylon.compiler.java.tools.LanguageCompiler.compile(LanguageCompiler.java:245)
	at com.redhat.ceylon.compiler.java.launcher.Main.compile(Main.java:650)
	at com.redhat.ceylon.compiler.java.launcher.Main.compile(Main.java:566)
	at com.redhat.ceylon.compiler.java.launcher.Main.compile(Main.java:556)
	at com.redhat.ceylon.compiler.CeylonCompileTool.run(CeylonCompileTool.java:503)
	... 15 more
Caused by: java.lang.AssertionError
	at com.sun.tools.javac.util.Assert.error(Assert.java:126)
	at com.sun.tools.javac.util.Assert.check(Assert.java:45)
	at com.sun.tools.javac.jvm.Gen.visitBreak(Gen.java:1642)
	at com.sun.tools.javac.tree.JCTree$JCBreak.accept(JCTree.java:1194)
	at com.sun.tools.javac.jvm.Gen.genDef(Gen.java:683)
	at com.sun.tools.javac.jvm.Gen.genStat(Gen.java:718)
	at com.sun.tools.javac.jvm.Gen.genStat(Gen.java:704)
	at com.sun.tools.javac.jvm.Gen.genStats(Gen.java:755)
	at com.sun.tools.javac.jvm.Gen.genStats(Gen.java:739)
	at com.sun.tools.javac.jvm.Gen.visitSwitch(Gen.java:1213)
	at com.sun.tools.javac.tree.JCTree$JCSwitch.accept(JCTree.java:961)
	at com.sun.tools.javac.jvm.Gen.genDef(Gen.java:683)
	at com.sun.tools.javac.jvm.Gen.genStat(Gen.java:718)
	at com.sun.tools.javac.jvm.Gen.genStat(Gen.java:704)
	at com.sun.tools.javac.jvm.Gen.genStats(Gen.java:755)
	at com.sun.tools.javac.jvm.Gen.visitBlock(Gen.java:1030)
	at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:783)
	at com.sun.tools.javac.jvm.Gen.genDef(Gen.java:683)
	at com.sun.tools.javac.jvm.Gen.genStat(Gen.java:718)
	at com.sun.tools.javac.jvm.Gen.genStat(Gen.java:704)
	at com.sun.tools.javac.jvm.Gen.visitLabelled(Gen.java:1107)
	at com.sun.tools.javac.tree.JCTree$JCLabeledStatement.accept(JCTree.java:936)
	at com.sun.tools.javac.jvm.Gen.genDef(Gen.java:683)
	at com.sun.tools.javac.jvm.Gen.genStat(Gen.java:718)
	at com.sun.tools.javac.jvm.Gen.genStat(Gen.java:704)
	at com.sun.tools.javac.jvm.Gen.genStats(Gen.java:755)
	at com.sun.tools.javac.jvm.Gen.visitLetExpr(Gen.java:2212)
	at com.sun.tools.javac.tree.JCTree$LetExpr.accept(JCTree.java:2114)
	at com.sun.tools.javac.jvm.Gen.genExpr(Gen.java:836)
	at com.sun.tools.javac.jvm.Gen.genArgs(Gen.java:855)
	at com.sun.tools.javac.jvm.Gen.visitApply(Gen.java:1693)
	at com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1323)
	at com.sun.tools.javac.jvm.Gen.genExpr(Gen.java:836)
	at com.sun.tools.javac.jvm.Gen.genArgs(Gen.java:855)
	at com.sun.tools.javac.jvm.Gen.visitApply(Gen.java:1693)
	at com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1323)
	at com.sun.tools.javac.jvm.Gen.genExpr(Gen.java:836)
	at com.sun.tools.javac.jvm.Gen.visitExec(Gen.java:1637)
	at com.sun.tools.javac.tree.JCTree$JCExpressionStatement.accept(JCTree.java:1169)
	at com.sun.tools.javac.jvm.Gen.genDef(Gen.java:683)
	at com.sun.tools.javac.jvm.Gen.genStat(Gen.java:718)
	at com.sun.tools.javac.jvm.Gen.genStat(Gen.java:704)
	at com.sun.tools.javac.jvm.Gen.genStats(Gen.java:755)
	at com.sun.tools.javac.jvm.Gen.visitBlock(Gen.java:1030)
	at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:783)
	at com.sun.tools.javac.jvm.Gen.genDef(Gen.java:683)
	at com.sun.tools.javac.jvm.Gen.genStat(Gen.java:718)
	at com.sun.tools.javac.jvm.Gen.genMethod(Gen.java:911)
	at com.sun.tools.javac.jvm.Gen.visitMethodDef(Gen.java:884)
	at com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:671)
	at com.sun.tools.javac.jvm.Gen.genDef(Gen.java:683)
	at com.sun.tools.javac.jvm.Gen.genClass(Gen.java:2249)
	at com.redhat.ceylon.compiler.java.tools.LanguageCompiler.genCodeUnlessError(LanguageCompiler.java:810)
	... 26 more
```

It works if I assign the `switch` to a local `value`, then assign this value to the member `foo`.

**Comment by tombentley** [comment]
The Java `let`/`switch` for the Ceylon `switch` expression is an argument to the setter for `foo`, thus a reference to `this` is on the stack. There's an assertion when visiting a Java `break` that the stack should be empty, which we're violating, hence the exception. I suppose we should simply remove the assertion.

**Comment by FroMage** [comment]
But does the VM let us do that? Did you try running the code?

**Comment by tombentley** [comment]
I did try running the code and it worked.
