### ISSUE TITLE
EnumeratedTypeError at runtime for switch + parametrized type

### ISSUE THREAD

**Issue by jpragey** [ceylon/ceylon-compiler#2269]
Running:
```ceylon
interface I<Param> {}

I<Param> myClass<Param>() 
        => object satisfies I<Param> {};

void f<Param>() {
    switch(bundle = myClass<Param>())
    case(is I<Param>) {}
}

shared void run() {
    f<String>();
}
```
breaks at runtime:
```
$ ceylon run org.bug3
Exception in thread "main" com.redhat.ceylon.compiler.java.language.EnumeratedTypeError: Supposedly exhaustive switch was not exhaustive
	at org.bug3.f_.f(run.ceylon:9)
	at org.bug3.run_.run(run.ceylon:14)
	at org.bug3.run_.main(run.ceylon)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at ceylon.modules.api.runtime.SecurityActions.invokeRunInternal(SecurityActions.java:57)
	at ceylon.modules.api.runtime.SecurityActions.invokeRun(SecurityActions.java:48)
	at ceylon.modules.api.runtime.AbstractRuntime.invokeRun(AbstractRuntime.java:110)
	at ceylon.modules.api.runtime.AbstractRuntime.execute(AbstractRuntime.java:176)
	at ceylon.modules.api.runtime.AbstractRuntime.execute(AbstractRuntime.java:160)
	at ceylon.modules.Main.execute(Main.java:69)
	at ceylon.modules.Main.main(Main.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.jboss.modules.Module.run(Module.java:312)
	at org.jboss.modules.Main.main(Main.java:460)
	at ceylon.modules.bootstrap.CeylonRunTool.run(CeylonRunTool.java:246)
	at com.redhat.ceylon.common.tools.CeylonTool.run(CeylonTool.java:390)
	at com.redhat.ceylon.common.tools.CeylonTool.execute(CeylonTool.java:327)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.redhat.ceylon.launcher.Launcher.runInJava7Checked(Launcher.java:114)
	at com.redhat.ceylon.launcher.Launcher.run(Launcher.java:41)
	at com.redhat.ceylon.launcher.Launcher.run(Launcher.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.redhat.ceylon.launcher.Bootstrap.run(Bootstrap.java:55)
	at com.redhat.ceylon.launcher.Bootstrap.main(Bootstrap.java:32)
```

**Comment by tombentley** [comment]
I think this is a systematic problem with local classes (and interfaces). It seems that `FunctionOrValueInterface` doesn't work with the algos in ModelUtil used for figuring out the applied types of things -- in particular when trying to construct the type argument map taking account of the type arguments applied to the qualifying type. I think @FroMage is probably better placed than me to fix this, since he wrote the `FunctionOrValueInterface` stuff.

**Comment by FroMage** [comment]
OK I'll take a look. The annoying thing about local types is that they can only be tested at runtime, so they are not in the typechecker tests, which makes them "hard" to test by @gavinking.

**Comment by FroMage** [comment]
Fixed.
