### ISSUE TITLE
Ceylon doc error when using Java 8 classes

### ISSUE THREAD

**Issue by vietj** [ceylon/ceylon-compiler#2286]
```
juliens-mbp-2:vertx-lang-ceylon julien$ ceylon doc io.vertx.ceylon.core/1.0.0 --src=src/main/ceylon 
Exception in thread "main" java.lang.IncompatibleClassChangeError: Implementing class
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:642)
	at com.redhat.ceylon.ceylondoc.ModulesClassLoader.findClass(ModulesClassLoader.java:53)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.redhat.ceylon.ceylondoc.CeylonDocModelLoader.loadClass(CeylonDocModelLoader.java:72)
	at com.redhat.ceylon.model.loader.impl.reflect.ReflectionModelLoader.lookupNewClassMirror(ReflectionModelLoader.java:104)
	at com.redhat.ceylon.ceylondoc.CeylonDocModuleManager$1.lookupNewClassMirror(CeylonDocModuleManager.java:88)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.lookupClassMirror(AbstractModelLoader.java:357)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.convertToDeclaration(AbstractModelLoader.java:1436)
	at com.redhat.ceylon.model.loader.impl.reflect.ReflectionModelLoader.loadPackage(ReflectionModelLoader.java:87)
	at com.redhat.ceylon.model.loader.model.LazyPackage.getMembers(LazyPackage.java:176)
	at com.redhat.ceylon.ceylondoc.CeylonDocTool.shouldInclude(CeylonDocTool.java:1048)
	at com.redhat.ceylon.ceylondoc.CeylonDocTool.getPackages(CeylonDocTool.java:1029)
	at com.redhat.ceylon.ceylondoc.CeylonDocTool.collectSubclasses(CeylonDocTool.java:701)
	at com.redhat.ceylon.ceylondoc.CeylonDocTool.makeDoc(CeylonDocTool.java:582)
	at com.redhat.ceylon.ceylondoc.CeylonDocTool.run(CeylonDocTool.java:570)
	at com.redhat.ceylon.common.tools.CeylonTool.run(CeylonTool.java:398)
	at com.redhat.ceylon.common.tools.CeylonTool.execute(CeylonTool.java:329)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.redhat.ceylon.launcher.Launcher.runInJava7Checked(Launcher.java:114)
	at com.redhat.ceylon.launcher.Launcher.run(Launcher.java:41)
	at com.redhat.ceylon.launcher.Launcher.run(Launcher.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.redhat.ceylon.launcher.Bootstrap.run(Bootstrap.java:55)
	at com.redhat.ceylon.launcher.Bootstrap.main(Bootstrap.java:32)
```

**Comment by FroMage** [comment]
Well, nobody can reproduce, closing.
