### ISSUE TITLE
compiler bug: null

### ISSUE THREAD

**Issue by bjansen** [ceylon/ceylon-compiler#2305]
I get the following errors when I build [`ceylon-ide-common`](https://github.com/ceylon/ceylon-ide-common/tree/wip-abstraction-completion-correction) (note that the given location `phasedUnits.ceylon:242` is totally irrelevant, and different between the CLI and Eclipse):

```
[ceylon-compile] /Users/bastien/Dev/ceylon/ceylon-ide-common/source/com/redhat/ceylon/ide/common/typechecker/phasedUnits.ceylon:242: error: compiler bug: null at com.redhat.ceylon.compiler.java.codegen.ExpressionTransformer.makeQualifiedDollarThis(ExpressionTransformer.java:4991)
[ceylon-compile] /Users/bastien/Dev/ceylon/ceylon-ide-common/source/com/redhat/ceylon/ide/common/typechecker/phasedUnits.ceylon:242: error: compiler bug: visitor didn't yield any result at com.redhat.ceylon.compiler.java.codegen.ExpressionTransformer.transformExpression(ExpressionTransformer.java:335)
[ceylon-compile] /Users/bastien/Dev/ceylon/ceylon-ide-common/source/com/redhat/ceylon/ide/common/typechecker/phasedUnits.ceylon:242: error: compiler bug: visitor didn't yield any result at unknown
[ceylon-compile] /Users/bastien/Dev/ceylon/ceylon-ide-common/source/com/redhat/ceylon/ide/common/typechecker/phasedUnits.ceylon:242: error: compiler bug: null at com.redhat.ceylon.compiler.java.codegen.ExpressionTransformer.makeQualifiedDollarThis(ExpressionTransformer.java:4991)
[ceylon-compile] /Users/bastien/Dev/ceylon/ceylon-ide-common/source/com/redhat/ceylon/ide/common/typechecker/phasedUnits.ceylon:242: error: compiler bug: visitor didn't yield any result at com.redhat.ceylon.compiler.java.codegen.ExpressionTransformer.transformExpression(ExpressionTransformer.java:335)
[ceylon-compile] /Users/bastien/Dev/ceylon/ceylon-ide-common/source/com/redhat/ceylon/ide/common/typechecker/phasedUnits.ceylon:242: error: compiler bug: visitor didn't yield any result at unknown
```

I think the errors are caused by [this class](https://github.com/ceylon/ceylon-ide-common/commit/22828b5b7739a809fec71fa9addd677c9311a02f#diff-51ebe14438514316eaa7c83cfbf1105eR244), and more specifically by these two calls in `createChange()`:

    initMultiEditChange(change);
    addEditToChange(change, createEdit(document));

**Comment by FroMage** [comment]
Minimal test case:

```ceylon

shared interface Interf {
    shared void initMultiEditChange(){}
}

shared interface InvocationCompletion {

    shared class Proposal() satisfies Interf {
        
        shared void createChange() {
            initMultiEditChange();
        }
    }
}
```

**Comment by FroMage** [comment]
Fixed.
