### ISSUE TITLE
compiler bug : unhandled declaration for method ref with missing type parameter

### ISSUE THREAD

**Issue by sgalles** [ceylon/ceylon-compiler#2312]
This code
```ceylon
void bar<Baz>(){}
shared void run(){
	value a = [bar];
}
```
compiled
```
compiler bug: unhandled declaration foo::run.a.Anonymous#bar with type TypeAlias at com.redhat.ceylon.compiler.java.codegen.AbstractTransformer.makeReifiedTypeArgumentResolved(AbstractTransformer.java:5174)
compiler bug: visitor didn't yield any result at com.redhat.ceylon.compiler.java.codegen.ExpressionTransformer.transformExpression(ExpressionTransformer.java:335)
compiler bug: visitor didn't yield any result at unknown
```

**Comment by gavinking** [comment]
This is just because the Java compiler doesn't yet support generic function refs. 

And I have not yet done https://github.com/ceylon/ceylon-spec/issues/1373.
