### ISSUE TITLE
NPE in `ceylon p2`

### ISSUE THREAD

**Issue by quintesse** [ceylon/ceylon-compiler#2314]
`ceylon p2 --offline --no-default-repositories --rep /home/ceylon/ceylon/ceylon-sdk/modules --out /home/ceylon/ceylon/ceylon-sdk/osgi/dist --categories /home/ceylon/ceylon/ceylon-sdk/osgi/p2/category.xml --category-prefix ceylon.sdk --repository-name "Ceylon SDK Bundles" ceylon.collection ceylon.dbc ceylon.file ceylon.html ceylon.interop.java ceylon.io ceylon.json ceylon.logging ceylon.math ceylon.net ceylon.process ceylon.promise ceylon.test ceylon.time ceylon.unicode ceylon.locale com.redhat.ceylon.war com.redhat.ceylon.test com.redhat.ceylon.testjvm`

When run from a different directory than the SDK results in an NPE.

**Comment by quintesse** [comment]
```
[ceylon-p2] java.lang.NullPointerException
[ceylon-p2] 	at com.redhat.ceylon.tools.p2.ModuleInfo.getAttribute(ModuleInfo.java:146)
[ceylon-p2] 	at com.redhat.ceylon.tools.p2.ModuleInfo.getOsgiProperties(ModuleInfo.java:152)
[ceylon-p2] 	at com.redhat.ceylon.tools.p2.CeylonP2Tool.printUnit(CeylonP2Tool.java:450)
[ceylon-p2] 	at com.redhat.ceylon.tools.p2.CeylonP2Tool.printContent(CeylonP2Tool.java:337)
[ceylon-p2] 	at com.redhat.ceylon.tools.p2.CeylonP2Tool.run(CeylonP2Tool.java:137)
[ceylon-p2] 	at com.redhat.ceylon.common.tools.CeylonTool.run(CeylonTool.java:448)
[ceylon-p2] 	at com.redhat.ceylon.common.tools.CeylonTool.execute(CeylonTool.java:357)
[ceylon-p2] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ceylon-p2] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ceylon-p2] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ceylon-p2] 	at java.lang.reflect.Method.invoke(Method.java:497)
[ceylon-p2] 	at com.redhat.ceylon.launcher.Launcher.runInJava7Checked(Launcher.java:114)
[ceylon-p2] 	at com.redhat.ceylon.ant.CeylonAntTask.executeCommandline(CeylonAntTask.java:229)
[ceylon-p2] 	at com.redhat.ceylon.ant.CeylonAntTask.execute(CeylonAntTask.java:186)
[ceylon-p2] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
[ceylon-p2] 	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
[ceylon-p2] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ceylon-p2] 	at java.lang.reflect.Method.invoke(Method.java:497)
[ceylon-p2] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
[ceylon-p2] 	at org.apache.tools.ant.Task.perform(Task.java:348)
[ceylon-p2] 	at org.apache.tools.ant.Target.execute(Target.java:435)
[ceylon-p2] 	at org.apache.tools.ant.Target.performTasks(Target.java:456)
[ceylon-p2] 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
[ceylon-p2] 	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
[ceylon-p2] 	at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
[ceylon-p2] 	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:441)
[ceylon-p2] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
[ceylon-p2] 	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
[ceylon-p2] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ceylon-p2] 	at java.lang.reflect.Method.invoke(Method.java:497)
[ceylon-p2] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
[ceylon-p2] 	at org.apache.tools.ant.Task.perform(Task.java:348)
[ceylon-p2] 	at org.apache.tools.ant.Target.execute(Target.java:435)
[ceylon-p2] 	at org.apache.tools.ant.Target.performTasks(Target.java:456)
[ceylon-p2] 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
[ceylon-p2] 	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
[ceylon-p2] 	at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
[ceylon-p2] 	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:441)
[ceylon-p2] 	at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:105)
[ceylon-p2] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ceylon-p2] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ceylon-p2] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ceylon-p2] 	at java.lang.reflect.Method.invoke(Method.java:497)
[ceylon-p2] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
[ceylon-p2] 	at org.apache.tools.ant.Task.perform(Task.java:348)
[ceylon-p2] 	at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
[ceylon-p2] 	at net.sf.antcontrib.logic.ForEach.executeSequential(ForEach.java:178)
[ceylon-p2] 	at net.sf.antcontrib.logic.ForEach.execute(ForEach.java:254)
[ceylon-p2] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
[ceylon-p2] 	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
[ceylon-p2] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ceylon-p2] 	at java.lang.reflect.Method.invoke(Method.java:497)
[ceylon-p2] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
[ceylon-p2] 	at org.apache.tools.ant.Task.perform(Task.java:348)
[ceylon-p2] 	at org.apache.tools.ant.Target.execute(Target.java:435)
[ceylon-p2] 	at org.apache.tools.ant.Target.performTasks(Target.java:456)
[ceylon-p2] 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
[ceylon-p2] 	at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
[ceylon-p2] 	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
[ceylon-p2] 	at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
[ceylon-p2] 	at org.apache.tools.ant.Main.runBuild(Main.java:851)
[ceylon-p2] 	at org.apache.tools.ant.Main.startAnt(Main.java:235)
[ceylon-p2] 	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
[ceylon-p2] 	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)
```

**Comment by FroMage** [comment]
I can't reproduce :(

**Comment by FroMage** [comment]
I could fix the NPE, but I don't think it will make it work, because if there are no OSGi attributes it means we couldn't load them and the generated metadata will be wrong, so we have to fix why we couldn't load them.

**Comment by quintesse** [comment]
I had to add the `--overrides` argument now to reproduce the error:

`ceylon p2 --overrides /home/ceylon/ceylon/ceylon-sdk/overrides.xml --offline --no-default-repositories --rep /home/ceylon/ceylon/ceylon-sdk/modules --out /home/ceylon/ceylon/ceylon-sdk/osgi/dist --categories /home/ceylon/ceylon/ceylon-sdk/osgi/p2/category.xml --category-prefix ceylon.sdk --repository-name "Ceylon SDK Bundles" ceylon.collection ceylon.dbc ceylon.file ceylon.html ceylon.interop.java ceylon.io ceylon.json ceylon.logging ceylon.math ceylon.net ceylon.process ceylon.promise ceylon.test ceylon.time ceylon.unicode ceylon.locale com.redhat.ceylon.war com.redhat.ceylon.test com.redhat.ceylon.testjvm`

Adding the `-cwd` option fixes the problem though:

`ceylon --cwd=/home/ceylon/ceylon/ceylon-sdk p2 --overrides /home/ceylon/ceylon/ceylon-sdk/overrides.xml --offline --no-default-repositories --rep /home/ceylon/ceylon/ceylon-sdk/modules --out /home/ceylon/ceylon/ceylon-sdk/osgi/dist --categories /home/ceylon/ceylon/ceylon-sdk/osgi/p2/category.xml --category-prefix ceylon.sdk --repository-name "Ceylon SDK Bundles" ceylon.collection ceylon.dbc ceylon.file ceylon.html ceylon.interop.java ceylon.io ceylon.json ceylon.logging ceylon.math ceylon.net ceylon.process ceylon.promise ceylon.test ceylon.time ceylon.unicode ceylon.locale com.redhat.ceylon.war com.redhat.ceylon.test com.redhat.ceylon.testjvm`

So it seems it really is some local file that affecting the outcome somehow.

**Comment by quintesse** [comment]
Btw, this has become low-prio because I know add the `--cwd` argument automatically to all Ceylon command run by our Ant tasks, so the problem isn't affecting the build anymore at least.

**Comment by FroMage** [comment]
I still can't reproduce, even with `--overrides`:

```
atlantis stephane 14:52 ceylon.language $ ../ceylon-dist/dist/bin/ceylon p2 --overrides ../ceylon-sdk/overrides.xml --offline --no-default-repositories --rep ../ceylon-sdk/modules --out ../ceylon-sdk/osgi/dist --categories ../ceylon-sdk/osgi/p2/category.xml --category-prefix ceylon.sdk --repository-name "Ceylon SDK Bundles" ceylon.collection ceylon.dbc ceylon.file ceylon.html ceylon.interop.java ceylon.io ceylon.json ceylon.logging ceylon.math ceylon.net ceylon.process ceylon.promise ceylon.test ceylon.time ceylon.unicode ceylon.locale com.redhat.ceylon.war com.redhat.ceylon.test com.redhat.ceylon.testjvm
Collecting modules from root module ceylon.collection
Module ceylon.collection/1.1.1 found in /home/stephane/src/java-eclipse/ceylon-sdk/modules
Module ceylon.language/1.1.1 not found in the specified repositories, nor in the output folder ../ceylon-sdk/osgi/dist/plugins
Collecting modules from root module ceylon.dbc
Module ceylon.dbc/1.1.1 found in /home/stephane/src/java-eclipse/ceylon-sdk/modules
Module ceylon.interop.java/1.1.1 found in /home/stephane/src/java-eclipse/ceylon-sdk/modules
Module ceylon.math/1.1.1 found in /home/stephane/src/java-eclipse/ceylon-sdk/modules
Module ceylon.time/1.1.1 found in /home/stephane/src/java-eclipse/ceylon-sdk/modules
Collecting modules from root module ceylon.file
Module ceylon.file/1.1.1 found in /home/stephane/src/java-eclipse/ceylon-sdk/modules
Collecting modules from root module ceylon.html
Module ceylon.html/1.1.1 found in /home/stephane/src/java-eclipse/ceylon-sdk/modules
Collecting modules from root module ceylon.interop.java
Collecting modules from root module ceylon.io
Module ceylon.io/1.1.1 found in /home/stephane/src/java-eclipse/ceylon-sdk/modules
Collecting modules from root module ceylon.json
Module ceylon.json/1.1.1 found in /home/stephane/src/java-eclipse/ceylon-sdk/modules
Collecting modules from root module ceylon.logging
Module ceylon.logging/1.1.1 found in /home/stephane/src/java-eclipse/ceylon-sdk/modules
Collecting modules from root module ceylon.math
Collecting modules from root module ceylon.net
Module ceylon.net/1.1.1 found in /home/stephane/src/java-eclipse/ceylon-sdk/modules
Module org.jboss.xnio.nio/3.3.0.Final found in http://modules.ceylon-lang.org/repo/1
Module org.jboss.xnio.api/3.3.0.Final found in http://modules.ceylon-lang.org/repo/1
Module org.jboss.logging/3.1.4.GA found in http://modules.ceylon-lang.org/repo/1
Module io.undertow.core/1.1.3.Final found in http://modules.ceylon-lang.org/repo/1
Module org.eclipse.jetty.alpn.api/1.0.0.fixed found in http://modules.ceylon-lang.org/repo/1
Collecting modules from root module ceylon.process
Module ceylon.process/1.1.1 found in /home/stephane/src/java-eclipse/ceylon-sdk/modules
Collecting modules from root module ceylon.promise
Module ceylon.promise/1.1.1 found in /home/stephane/src/java-eclipse/ceylon-sdk/modules
Collecting modules from root module ceylon.test
Module ceylon.test/1.1.1 found in /home/stephane/src/java-eclipse/ceylon-sdk/modules
Collecting modules from root module ceylon.time
Collecting modules from root module ceylon.unicode
Module ceylon.unicode/1.1.1 found in /home/stephane/src/java-eclipse/ceylon-sdk/modules
Collecting modules from root module ceylon.locale
Module ceylon.locale/1.1.1 found in /home/stephane/src/java-eclipse/ceylon-sdk/modules
Collecting modules from root module com.redhat.ceylon.war
Module com.redhat.ceylon.war/1.1.1 found in /home/stephane/src/java-eclipse/ceylon-sdk/modules
Module com.redhat.ceylon.common/1.1.1 not found in the specified repositories, nor in the output folder ../ceylon-sdk/osgi/dist/plugins
Module javax.servlet/3.1.0 found in http://modules.ceylon-lang.org/repo/1
Collecting modules from root module com.redhat.ceylon.test
Module com.redhat.ceylon.test/1.1.1 found in /home/stephane/src/java-eclipse/ceylon-sdk/modules
Collecting modules from root module com.redhat.ceylon.testjvm
Module com.redhat.ceylon.testjvm/1.1.1 found in /home/stephane/src/java-eclipse/ceylon-sdk/modules
Module org.jboss.modules/1.3.3.Final not found in the specified repositories, nor in the output folder ../ceylon-sdk/osgi/dist/plugins
Module ceylon.runtime/1.1.1 not found in the specified repositories, nor in the output folder ../ceylon-sdk/osgi/dist/plugins
Collecting features from folder ../ceylon-sdk/osgi/dist/features
Parsing categories file ../ceylon-sdk/osgi/p2/category.xml
Category module-bundles found
Generating artifacts.xml
Generating content.xml
```

**Comment by quintesse** [comment]
Hmm no idea, I copy your line exactly, I make a `test` folder at the same level as the `ceylon-sdk` folder, I go there and execute it and I get my NPE. (Running from the `ceylon-sdk` folder itself works of course)

**Comment by FroMage** [comment]
Can you reproduce it from the p2 tools tests?
