### ISSUE TITLE
Can't spread stream in Java varargs

### ISSUE THREAD

**Issue by bjansen** [ceylon/ceylon-compiler#2319]
Given the following Java contract:

```java
public interface JavaInterface<T> {

    boolean in(T... values);
}
```

And the following ceylon code:

```ceylon
void foo(JavaInterface<String> intf, {String*} vals) {
    intf.\iin(*vals);
}
```

I get this error:

```
source/mymodule/module.ceylon:3: error: compiler bug: Index: 0, Size: 0 at java.util.ArrayList.rangeCheck(ArrayList.java:653)
    import java.base "7";
                        ^
source/mymodule/module.ceylon:3: error: compiler bug: visitor didn't yield any result at com.redhat.ceylon.compiler.java.codegen.ExpressionTransformer.transformExpression(ExpressionTransformer.java:335)
    import java.base "7";
                        ^
source/mymodule/module.ceylon:3: error: compiler bug: visitor didn't yield any result at unknown
    import java.base "7";
                        ^
ceylon compile: There were 3 errors
```

Unfortunately my real code is using a jOOQ interface, so I can't change it to `in(String... values)`.

**Comment by bjansen** [comment]
Works if I transform the `{String*}` to a `{java.lang.String*}`

**Comment by FroMage** [comment]
Can you believe the same code works if the `T` is declared on the method and not the class? We had tests for the former but not the latter.

**Comment by FroMage** [comment]
Fixed.
