### ISSUE TITLE
NPE for metamodel + local class + union types

### ISSUE THREAD

**Issue by jpragey** [ceylon/ceylon-compiler#2334]
Hi,
Running:
```ceylon
interface I<T> {}

class MyImpl() satisfies I<String>{}

void work<in Container>(
    Attribute<Container, I<String>>|Attribute<Container, String, String> attribute) 
{
    value v = if(is Attribute<Container, I<String>> attribute) then 0 else 1; // NPE here
}

shared void run() {
    void doRun() { 
        class MyContainer() {
            shared MyImpl myI = MyImpl();
        }
        work(`MyContainer.myI`); 
    }
    doRun();
}
```
causes:
```
$ ceylon run org.bug1
ceylon run: null
java.lang.NullPointerException
	at com.redhat.ceylon.model.loader.model.FunctionOrValueInterface.getContainer(FunctionOrValueInterface.java:39)
	at com.redhat.ceylon.model.typechecker.model.Declaration.isClassOrInterfaceMember(Declaration.java:321)
	at com.redhat.ceylon.model.typechecker.model.ModelUtil.countTypeParameters(ModelUtil.java:947)
	at com.redhat.ceylon.model.typechecker.model.ModelUtil.getTypeArgumentMap(ModelUtil.java:1008)
	at com.redhat.ceylon.model.typechecker.model.TypeDeclaration.appliedType(TypeDeclaration.java:193)
	at com.redhat.ceylon.compiler.java.runtime.model.TypeDescriptor$FunctionOrValue.makeProducedType(TypeDescriptor.java:636)
	at com.redhat.ceylon.compiler.java.runtime.model.TypeDescriptor$FunctionOrValue.toProducedType(TypeDescriptor.java:626)
	at com.redhat.ceylon.compiler.java.runtime.model.TypeDescriptor$Member.toType(TypeDescriptor.java:738)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.getProducedType(Metamodel.java:328)
	at com.redhat.ceylon.compiler.java.runtime.model.TypeDescriptor$Member.toType(TypeDescriptor.java:737)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.getProducedType(Metamodel.java:328)
	at com.redhat.ceylon.compiler.java.runtime.model.TypeDescriptor$Class.toProducedType(TypeDescriptor.java:312)
	at com.redhat.ceylon.compiler.java.runtime.model.TypeDescriptor$Class.toType(TypeDescriptor.java:301)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.getProducedType(Metamodel.java:328)
	at com.redhat.ceylon.compiler.java.runtime.model.TypeDescriptor.is(TypeDescriptor.java:1361)
	at com.redhat.ceylon.compiler.java.runtime.model.TypeDescriptor$Class.is(TypeDescriptor.java:263)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.isReified(Metamodel.java:294)
	at com.redhat.ceylon.compiler.java.Util.isReified(Util.java:63)
	at org.bug1.work_.work(run.ceylon:12)
	at org.bug1.run_$1doRun_.doRun(run.ceylon:20)
	at org.bug1.run_.run(run.ceylon:22)
	at org.bug1.run_.main(run.ceylon)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at ceylon.modules.api.runtime.SecurityActions.invokeRunInternal(SecurityActions.java:57)
	at ceylon.modules.api.runtime.SecurityActions.invokeRun(SecurityActions.java:48)
	at ceylon.modules.api.runtime.AbstractRuntime.invokeRun(AbstractRuntime.java:72)
	at ceylon.modules.api.runtime.AbstractRuntime.execute(AbstractRuntime.java:119)
	at ceylon.modules.api.runtime.AbstractRuntime.execute(AbstractRuntime.java:103)
	at ceylon.modules.Main.execute(Main.java:69)
	at ceylon.modules.Main.main(Main.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.jboss.modules.Module.run(Module.java:312)
	at org.jboss.modules.Main.main(Main.java:460)
	at ceylon.modules.bootstrap.CeylonRunTool.run(CeylonRunTool.java:244)
	at com.redhat.ceylon.common.tools.CeylonTool.run(CeylonTool.java:490)
	at com.redhat.ceylon.common.tools.CeylonTool.execute(CeylonTool.java:380)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.redhat.ceylon.launcher.Launcher.runInJava7Checked(Launcher.java:114)
	at com.redhat.ceylon.launcher.Launcher.run(Launcher.java:41)
	at com.redhat.ceylon.launcher.Launcher.run(Launcher.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.redhat.ceylon.launcher.Bootstrap.run(Bootstrap.java:55)
	at com.redhat.ceylon.launcher.Bootstrap.main(Bootstrap.java:32)
```

**Comment by FroMage** [comment]
Fixed.
