### ISSUE TITLE
backend error if native impl precedes header with default

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-compiler#2367]
For:

```ceylon
native("jvm") class NC() {}
native("js") class NC() {}

native class NC() {
    shared void foo() => print("default impl");
}

shared void run() {
    NC().foo();
}
```

you get:

```
$ ceylon compile simple && ceylon run simple
source/simple/run.ceylon:9: error: cannot find symbol
    NC().foo();
      ^
  symbol:   method foo()
  location: class NC
Note: Created module simple/1.0.0
ceylon compile: Fatal error: The compiler exited abnormally (4) due to a bug in the compiler.
Please report it:
 https://github.com/ceylon/ceylon-compiler/issues/new
Please include:

* the stacktrace printed below
* a description of what you were trying to compile.

Thank you!
com.redhat.ceylon.compiler.CompilerBugException: Bug
	at com.redhat.ceylon.compiler.CeylonCompileTool.handleExitCode(CeylonCompileTool.java:557)
	at com.redhat.ceylon.compiler.CeylonCompileTool.run(CeylonCompileTool.java:539)
	at com.redhat.ceylon.common.tools.CeylonTool.run(CeylonTool.java:491)
	at com.redhat.ceylon.common.tools.CeylonTool.execute(CeylonTool.java:380)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.redhat.ceylon.launcher.Launcher.runInJava7Checked(Launcher.java:114)
	at com.redhat.ceylon.launcher.Launcher.run(Launcher.java:41)
	at com.redhat.ceylon.launcher.Launcher.run(Launcher.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.redhat.ceylon.launcher.Bootstrap.run(Bootstrap.java:55)
	at com.redhat.ceylon.launcher.Bootstrap.main(Bootstrap.java:32)
Caused by: java.lang.NullPointerException
	at com.sun.tools.javac.comp.TransTypes.retype(TransTypes.java:160)
	at com.sun.tools.javac.comp.TransTypes.visitApply(TransTypes.java:605)
	at com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1323)
	at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
	at com.sun.tools.javac.comp.TransTypes.translate(TransTypes.java:429)
	at com.sun.tools.javac.comp.TransTypes.visitExec(TransTypes.java:568)
	at com.sun.tools.javac.tree.JCTree$JCExpressionStatement.accept(JCTree.java:1169)
	at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
	at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:70)
	at com.sun.tools.javac.tree.TreeTranslator.visitBlock(TreeTranslator.java:160)
	at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:783)
	at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
	at com.sun.tools.javac.comp.TransTypes.translate(TransTypes.java:429)
	at com.sun.tools.javac.comp.TransTypes.visitMethodDef(TransTypes.java:463)
	at com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:671)
	at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
	at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:70)
	at com.sun.tools.javac.tree.TreeTranslator.visitClassDef(TreeTranslator.java:134)
	at com.sun.tools.javac.comp.TransTypes.translateClass(TransTypes.java:890)
	at com.sun.tools.javac.comp.TransTypes.visitClassDef(TransTypes.java:450)
	at com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:593)
	at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
	at com.sun.tools.javac.comp.TransTypes.translate(TransTypes.java:429)
	at com.sun.tools.javac.comp.TransTypes.translateTopLevelClass(TransTypes.java:917)
	at com.sun.tools.javac.main.JavaCompiler.desugar(JavaCompiler.java:1376)
	at com.redhat.ceylon.compiler.java.tools.LanguageCompiler.desugar(LanguageCompiler.java:866)
	at com.sun.tools.javac.main.JavaCompiler.desugar(JavaCompiler.java:1272)
	at com.sun.tools.javac.main.JavaCompiler.compile2(JavaCompiler.java:871)
	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:829)
	at com.redhat.ceylon.compiler.java.tools.LanguageCompiler.compile(LanguageCompiler.java:263)
	at com.redhat.ceylon.compiler.java.launcher.Main.compile(Main.java:650)
	at com.redhat.ceylon.compiler.java.launcher.Main.compile(Main.java:566)
	at com.redhat.ceylon.compiler.java.launcher.Main.compile(Main.java:556)
	at com.redhat.ceylon.compiler.CeylonCompileTool.run(CeylonCompileTool.java:538)
	... 15 more
jvasileff@orion:simple$ 
```

**Comment by quintesse** [comment]
I actually don't think these are backend errors but something we should prohibit in the typechecker.

**Comment by quintesse** [comment]
Moving this to https://github.com/ceylon/ceylon-spec/issues/1446
