### ISSUE TITLE
ceylon test: inspect the tested module to determine version of the test framework to load

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-compiler#2426]
AFAICT, `ceylon test` loads the *latest* available version of `com.redhat.ceylon.testjvm` (e.g. `1.2.1`), causing a conflict with the version of `ceylon.test` specified in the tested module's `module.ceylon` (e.g. `1.2.0`).

Using the `1.2.0` cli, if you attempt to run tests on a module that imports `1.2.0` when `testjvm` version `1.2.1` is available in `~/.ceylon/repo`, you get:

```
$ ceylon test test.com.vasileff.ceylon.xmath.common
Exception in thread "main" ceylon.language.AssertionError "Assertion failed
	violated is CeylonModuleLoader loader = ceylonModuleLoader"
	at com.redhat.ceylon.testjvm.Runner.loadModule$priv$(tool.ceylon:129)
	at com.redhat.ceylon.testjvm.Runner.loadModules$priv$(tool.ceylon:124)
	at com.redhat.ceylon.testjvm.Runner.run(tool.ceylon:53)
	at com.redhat.ceylon.testjvm.run_.run(tool.ceylon:36)
	at com.redhat.ceylon.testjvm.run_.main(tool.ceylon)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at ceylon.modules.api.runtime.SecurityActions.invokeRunInternal(SecurityActions.java:57)
	at ceylon.modules.api.runtime.SecurityActions.invokeRun(SecurityActions.java:48)
	at ceylon.modules.api.runtime.AbstractRuntime.invokeRun(AbstractRuntime.java:75)
	at ceylon.modules.api.runtime.AbstractRuntime.execute(AbstractRuntime.java:122)
	at ceylon.modules.api.runtime.AbstractRuntime.execute(AbstractRuntime.java:106)
	at ceylon.modules.Main.execute(Main.java:69)
	at ceylon.modules.Main.main(Main.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.jboss.modules.Module.run(Module.java:312)
	at org.jboss.modules.Main.main(Main.java:460)
	at ceylon.modules.bootstrap.CeylonRunTool.run(CeylonRunTool.java:244)
	at ceylon.modules.bootstrap.CeylonTestTool.run(CeylonTestTool.java:174)
	at com.redhat.ceylon.common.tools.CeylonTool.run(CeylonTool.java:491)
	at com.redhat.ceylon.common.tools.CeylonTool.execute(CeylonTool.java:380)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.redhat.ceylon.launcher.Launcher.runInJava7Checked(Launcher.java:114)
	at com.redhat.ceylon.launcher.Launcher.run(Launcher.java:41)
	at com.redhat.ceylon.launcher.Launcher.run(Launcher.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.redhat.ceylon.launcher.Bootstrap.run(Bootstrap.java:55)
	at com.redhat.ceylon.launcher.Bootstrap.main(Bootstrap.java:32)
```

**Comment by jvasileff** [comment]
Ha, I could also rtfm:

```
        --version=<version>
            Specifies version of test module, which will be used, if no value is set, then the latest available version will be used.
```
and indeed, `ceylon test --version 1.2.0  test.com.vasileff.ceylon.xmath.common` works. But I do think this should be automatic, somehow.

**Comment by thradec** [comment]
> Edit: any reason not to just treat tests more like ceylon run --run ceylon.test::entryPoint -- moduleToTest (and some extra args), letting moduleToTest's dependencies handle loading the test framework?

it wouldn't be possible to run tests from several modules together, but for one module it would work probably

**Comment by thradec** [comment]
Should be fixed.
